Laebe_1year_male_10_sygdomstekst                                                               <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Huuli, miehet"
Mundhule_1year_male_20_sygdomstekst                                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suuontelo, miehet"
Spytkirtel_1year_male_30_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Sylkirauhaset, miehet"
Oropharynx_1year_male_40_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suunielu, miehet"
Nasopharynx_1year_male_41_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nenänielu, miehet"
Hypopharynx_1year_male_50_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Alanielu, miehet"
Pharynx_daarligt_defineret_1year_male_51_sygdomstekst                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nielu, määrittelemätön, miehet"
Spiseror_1year_male_60_sygdomstekst                                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ruokatorvi, miehet"
Mave_1year_male_70_sygdomstekst                                                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Maha, miehet"
Tyndtarm_1year_male_80_sygdomstekst                                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ohutsuoli, miehet"
Tyktarm_1year_male_90_sygdomstekst                                                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Paksusuoli, miehet"
Endetarm_og_anus_1year_male_100_sygdomstekst                                                   <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Peräsuoli ja anus, miehet"
Lever_1year_male_110_sygdomstekst                                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Maksa, miehet"
Galdeblaere_og_galdeveje_1year_male_120_sygdomstekst                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Sappirakko ja sappitiet, miehet"
Bugspytkirtel_1year_male_130_sygdomstekst                                                      <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Haima, miehet"
Naese_og_bihuler_1year_male_140_sygdomstekst                                                   <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nenä, miehet"
Strube_1year_male_150_sygdomstekst                                                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kurkunpää, miehet"
Lunge_inkl_luftror_1year_male_160_sygdomstekst                                                 <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Keuhko, miehet"
Lungehinde_1year_male_170_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Keuhkopussi, miehet"
Bryst_1year_male_180_sygdomstekst                                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Rinta, miehet"
Livmoderhals_1year_male_190_sygdomstekst                                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunkaula, miehet"
Livmoder_1year_male_200_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunrunko, miehet"
Livmoder_uden_specifikation_1year_male_210_sygdomstekst                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muu kohtusyöpä, miehet"
Aeggestok_aeggeleder_mv_1year_male_220_sygdomstekst                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Munasarjat, miehet"
Ovrige_kvindelige_konsorganer_1year_male_230_sygdomstekst                                      <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muut naisen sukuelimet, miehet"
Prostata_1year_male_240_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Eturauhanen, miehet"
Testikel_1year_male_250_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kives, miehet"
Penis_og_andre_mandlige_konsorganer_1year_male_260_sygdomstekst                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muut miehen sukuelimet, miehet"
Nyre_1year_male_270_sygdomstekst                                                               <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Munuainen, miehet"
Blaere_og_andre_urinveje_1year_male_280_sygdomstekst                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Virtsarakko ja muut virtsaelimet, miehet"
Modermaerkekraeft_hud_1year_male_290_sygdomstekst                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ihomelanooma, miehet"
Anden_hud_ikke_modermaerke_1year_male_300_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Iho, ei melanooma, miehet"
Oje_1year_male_310_sygdomstekst                                                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Silmä, miehet"
Hjerne_og_centralnervesystem_1year_male_320_sygdomstekst                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Aivot ja hermosto, miehet"
Skjoldbruskkirtel_1year_male_330_sygdomstekst                                                  <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kilpirauhanen, miehet"
Knogle_1year_male_340_sygdomstekst                                                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Luu, miehet"
Bindevaev_1year_male_350_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Pehmytkudos, miehet"
Non_Hodgkin_lymfom_1year_male_360_sygdomstekst                                                 <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Non-Hodgkin -lymfooma, miehet"
Hodgkins_lymfom_1year_male_370_sygdomstekst                                                    <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Hodgkinin lymfooma, miehet"
Myelomatose_1year_male_380_sygdomstekst                                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Myelooma, miehet"
Leukaemi_1year_male_400_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, miehet"
Akut_lymfatisk_leukaemi_1year_male_401_sygdomstekst                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen akuutti, miehet"
Kronisk_lymfatisk_leukaemi_1year_male_402_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen krooninen, miehet"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403_sygdomstekst                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen muu tai määrittämätön, miehet"
Akut_myeloid_leukaemi_1year_male_404_sygdomstekst                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen akuutti, miehet"
Kronisk_myeloid_leukaemi_1year_male_405_sygdomstekst                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen krooninen, miehet"
Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406_sygdomstekst                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen muu tai määrittämätön, miehet"
Leukaemi_uspecificerede_celler_1year_male_407_sygdomstekst                                     <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, solutyyppi määrittelemätön, miehet"
Andre_specificerede_1year_male_410_sygdomstekst                                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muu määritelty sijainti, miehet"
Ukendte_og_daarligt_definerede_1year_male_420_sygdomstekst                                     <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Tuntematon ja määrittelemätön sijainti, miehet"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970_sygdomstekst             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, rinta- ja eturauhassyövät, miehet"
Alle_kraeftformer_1year_male_980_sygdomstekst                                                  <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät, miehet"
Alle_kraeftformer_undtagen_anden_hud_1year_male_990_sygdomstekst                               <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, miehet"
Laebe_mundhule_og_svaelg_1year_male_510_sygdomstekst                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suu ja nielu, miehet"
Tyk_og_endetarm_1year_male_520_sygdomstekst                                                    <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Paksu- ja peräsuoli, miehet"
Basocellulaere_carcinomer_1year_male_888_sygdomstekst                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Basalioomat, miehet"

Laebe_1year_female_10_sygdomstekst                                                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Huuli, naiset"
Mundhule_1year_female_20_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suuontelo, naiset"
Spytkirtel_1year_female_30_sygdomstekst                                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Sylkirauhaset, naiset"
Oropharynx_1year_female_40_sygdomstekst                                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suunielu, naiset"
Nasopharynx_1year_female_41_sygdomstekst                                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nenänielu, naiset"
Hypopharynx_1year_female_50_sygdomstekst                                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Alanielu, naiset"
Pharynx_daarligt_defineret_1year_female_51_sygdomstekst                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nielu, määrittelemätön, naiset"
Spiseror_1year_female_60_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ruokatorvi, naiset"
Mave_1year_female_70_sygdomstekst                                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Maha, naiset"
Tyndtarm_1year_female_80_sygdomstekst                                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ohutsuoli, naiset"
Tyktarm_1year_female_90_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Paksusuoli, naiset"
Endetarm_og_anus_1year_female_100_sygdomstekst                                                 <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Peräsuoli ja anus, naiset"
Lever_1year_female_110_sygdomstekst                                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Maksa, naiset"
Galdeblaere_og_galdeveje_1year_female_120_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Sappirakko ja sappitiet, naiset"
Bugspytkirtel_1year_female_130_sygdomstekst                                                    <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Haima, naiset"
Naese_og_bihuler_1year_female_140_sygdomstekst                                                 <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Nenä, naiset"
Strube_1year_female_150_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kurkunpää, naiset"
Lunge_inkl_luftror_1year_female_160_sygdomstekst                                               <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Keuhko, naiset"
Lungehinde_1year_female_170_sygdomstekst                                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Keuhkopussi, naiset"
Bryst_1year_female_180_sygdomstekst                                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Rinta, naiset"
Livmoderhals_1year_female_190_sygdomstekst                                                     <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunkaula, naiset"
Livmoder_1year_female_200_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunrunko, naiset"
Livmoder_uden_specifikation_1year_female_210_sygdomstekst                                      <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muu kohtusyöpä, naiset"
Aeggestok_aeggeleder_mv_1year_female_220_sygdomstekst                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Munasarjat, naiset"
Ovrige_kvindelige_konsorganer_1year_female_230_sygdomstekst                                    <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muut naisen sukuelimet, naiset"
Prostata_1year_female_240_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Eturauhanen, naiset"
Testikel_1year_female_250_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kives, naiset"
Penis_og_andre_mandlige_konsorganer_1year_female_260_sygdomstekst                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muut miehen sukuelimet, naiset"
Nyre_1year_female_270_sygdomstekst                                                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Munuainen, naiset"
Blaere_og_andre_urinveje_1year_female_280_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Virtsarakko ja muut virtsaelimet, naiset"
Modermaerkekraeft_hud_1year_female_290_sygdomstekst                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Ihomelanooma, naiset"
Anden_hud_ikke_modermaerke_1year_female_300_sygdomstekst                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Iho, ei melanooma, naiset"
Oje_1year_female_310_sygdomstekst                                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Silmä, naiset"
Hjerne_og_centralnervesystem_1year_female_320_sygdomstekst                                     <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Aivot ja hermosto, naiset"
Skjoldbruskkirtel_1year_female_330_sygdomstekst                                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kilpirauhanen, naiset"
Knogle_1year_female_340_sygdomstekst                                                           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Luu, naiset"
Bindevaev_1year_female_350_sygdomstekst                                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Pehmytkudos, naiset"
Non_Hodgkin_lymfom_1year_female_360_sygdomstekst                                               <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Non-Hodgkin -lymfooma, naiset"
Hodgkins_lymfom_1year_female_370_sygdomstekst                                                  <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Hodgkinin lymfooma, naiset"
Myelomatose_1year_female_380_sygdomstekst                                                      <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Myelooma, naiset"
Leukaemi_1year_female_400_sygdomstekst                                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, naiset"
Akut_lymfatisk_leukaemi_1year_female_401_sygdomstekst                                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen akuutti, naiset"
Kronisk_lymfatisk_leukaemi_1year_female_402_sygdomstekst                                       <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen krooninen, naiset"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403_sygdomstekst                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen muu tai määrittämätön, naiset"
Akut_myeloid_leukaemi_1year_female_404_sygdomstekst                                            <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen akuutti, naiset"
Kronisk_myeloid_leukaemi_1year_female_405_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen krooninen, naiset"
Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406_sygdomstekst                          <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen muu tai määrittämätön, naiset"
Leukaemi_uspecificerede_celler_1year_female_407_sygdomstekst                                   <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, solutyyppi määrittelemätön, naiset"
Andre_specificerede_1year_female_410_sygdomstekst                                              <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Muu määritelty sijainti, naiset"
Ukendte_og_daarligt_definerede_1year_female_420_sygdomstekst                                   <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Tuntematon ja määrittelemätön sijainti, naiset"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970_sygdomstekst           <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, rinta- ja eturauhassyövät, naiset"
Alle_kraeftformer_1year_female_980_sygdomstekst                                                <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät, naiset"
Alle_kraeftformer_undtagen_anden_hud_1year_female_990_sygdomstekst                             <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, naiset"
Laebe_mundhule_og_svaelg_1year_female_510_sygdomstekst                                         <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Suu ja nielu, naiset"
Tyk_og_endetarm_1year_female_520_sygdomstekst                                                  <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Paksu- ja peräsuoli, naiset"
Basocellulaere_carcinomer_1year_female_888_sygdomstekst                                        <-             "Parannus suhteellisessa 1-vuotiselossaolo-osuudessa, NORDCAN\n Basalioomat, naiset"

Laebe_5year_male_10_sygdomstekst                                                               <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Huuli, miehet"
Mundhule_5year_male_20_sygdomstekst                                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suuontelo, miehet"
Spytkirtel_5year_male_30_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Sylkirauhaset, miehet"
Oropharynx_5year_male_40_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suunielu, miehet"
Nasopharynx_5year_male_41_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nenänielu, miehet"
Hypopharynx_5year_male_50_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Alanielu, miehet"
Pharynx_daarligt_defineret_5year_male_51_sygdomstekst                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nielu, määrittelemätön, miehet"
Spiseror_5year_male_60_sygdomstekst                                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ruokatorvi, miehet"
Mave_5year_male_70_sygdomstekst                                                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Maha, miehet"
Tyndtarm_5year_male_80_sygdomstekst                                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ohutsuoli, miehet"
Tyktarm_5year_male_90_sygdomstekst                                                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Paksusuoli, miehet"
Endetarm_og_anus_5year_male_100_sygdomstekst                                                   <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Peräsuoli ja anus, miehet"
Lever_5year_male_110_sygdomstekst                                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Maksa, miehet"
Galdeblaere_og_galdeveje_5year_male_120_sygdomstekst                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Sappirakko ja sappitiet, miehet"
Bugspytkirtel_5year_male_130_sygdomstekst                                                      <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Haima, miehet"
Naese_og_bihuler_5year_male_140_sygdomstekst                                                   <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nenä, miehet"
Strube_5year_male_150_sygdomstekst                                                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kurkunpää, miehet"
Lunge_inkl_luftror_5year_male_160_sygdomstekst                                                 <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Keuhko, miehet"
Lungehinde_5year_male_170_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Keuhkopussi, miehet"
Bryst_5year_male_180_sygdomstekst                                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Rinta, miehet"
Livmoderhals_5year_male_190_sygdomstekst                                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunkaula, miehet"
Livmoder_5year_male_200_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunrunko, miehet"
Livmoder_uden_specifikation_5year_male_210_sygdomstekst                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muu kohtusyöpä, miehet"
Aeggestok_aeggeleder_mv_5year_male_220_sygdomstekst                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Munasarjat, miehet"
Ovrige_kvindelige_konsorganer_5year_male_230_sygdomstekst                                      <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muut naisen sukuelimet, miehet"
Prostata_5year_male_240_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Eturauhanen, miehet"
Testikel_5year_male_250_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kives, miehet"
Penis_og_andre_mandlige_konsorganer_5year_male_260_sygdomstekst                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muut miehen sukuelimet, miehet"
Nyre_5year_male_270_sygdomstekst                                                               <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Munuainen, miehet"
Blaere_og_andre_urinveje_5year_male_280_sygdomstekst                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Virtsarakko ja muut virtsaelimet, miehet"
Modermaerkekraeft_hud_5year_male_290_sygdomstekst                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ihomelanooma, miehet"
Anden_hud_ikke_modermaerke_5year_male_300_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Iho, ei melanooma, miehet"
Oje_5year_male_310_sygdomstekst                                                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Silmä, miehet"
Hjerne_og_centralnervesystem_5year_male_320_sygdomstekst                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Aivot ja hermosto, miehet"
Skjoldbruskkirtel_5year_male_330_sygdomstekst                                                  <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kilpirauhanen, miehet"
Knogle_5year_male_340_sygdomstekst                                                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Luu, miehet"
Bindevaev_5year_male_350_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Pehmytkudos, miehet"
Non_Hodgkin_lymfom_5year_male_360_sygdomstekst                                                 <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Non-Hodgkin -lymfooma, miehet"
Hodgkins_lymfom_5year_male_370_sygdomstekst                                                    <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Hodgkinin lymfooma, miehet"
Myelomatose_5year_male_380_sygdomstekst                                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Myelooma, miehet"
Leukaemi_5year_male_400_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, miehet"
Akut_lymfatisk_leukaemi_5year_male_401_sygdomstekst                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen akuutti, miehet"
Kronisk_lymfatisk_leukaemi_5year_male_402_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen krooninen, miehet"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403_sygdomstekst                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen muu tai määrittämätön, miehet"
Akut_myeloid_leukaemi_5year_male_404_sygdomstekst                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen akuutti, miehet"
Kronisk_myeloid_leukaemi_5year_male_405_sygdomstekst                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen krooninen, miehet"
Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406_sygdomstekst                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen muu tai määrittämätön, miehet"
Leukaemi_uspecificerede_celler_5year_male_407_sygdomstekst                                     <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, solutyyppi määrittelemätön, miehet"
Andre_specificerede_5year_male_410_sygdomstekst                                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muu määritelty sijainti, miehet"
Ukendte_og_daarligt_definerede_5year_male_420_sygdomstekst                                     <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Tuntematon ja määrittelemätön sijainti, miehet"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970_sygdomstekst             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, rinta- ja eturauhassyövät, miehet"
Alle_kraeftformer_5year_male_980_sygdomstekst                                                  <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät, miehet"
Alle_kraeftformer_undtagen_anden_hud_5year_male_990_sygdomstekst                               <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, miehet"
Laebe_mundhule_og_svaelg_5year_male_510_sygdomstekst                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suu ja nielu, miehet"
Tyk_og_endetarm_5year_male_520_sygdomstekst                                                    <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Paksu- ja peräsuoli, miehet"
Basocellulaere_carcinomer_5year_male_888_sygdomstekst                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Basalioomat, miehet"


Laebe_5year_female_10_sygdomstekst                                                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Huuli, naiset"
Mundhule_5year_female_20_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suuontelo, naiset"
Spytkirtel_5year_female_30_sygdomstekst                                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Sylkirauhaset, naiset"
Oropharynx_5year_female_40_sygdomstekst                                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suunielu, naiset"
Nasopharynx_5year_female_41_sygdomstekst                                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nenänielu, naiset"
Hypopharynx_5year_female_50_sygdomstekst                                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Alanielu, naiset"
Pharynx_daarligt_defineret_5year_female_51_sygdomstekst                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nielu, määrittelemätön, naiset"
Spiseror_5year_female_60_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ruokatorvi, naiset"
Mave_5year_female_70_sygdomstekst                                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Maha, naiset"
Tyndtarm_5year_female_80_sygdomstekst                                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ohutsuoli, naiset"
Tyktarm_5year_female_90_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Paksusuoli, naiset"
Endetarm_og_anus_5year_female_100_sygdomstekst                                                 <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Peräsuoli ja anus, naiset"
Lever_5year_female_110_sygdomstekst                                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Maksa, naiset"
Galdeblaere_og_galdeveje_5year_female_120_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Sappirakko ja sappitiet, naiset"
Bugspytkirtel_5year_female_130_sygdomstekst                                                    <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Haima, naiset"
Naese_og_bihuler_5year_female_140_sygdomstekst                                                 <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Nenä, naiset"
Strube_5year_female_150_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kurkunpää, naiset"
Lunge_inkl_luftror_5year_female_160_sygdomstekst                                               <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Keuhko, naiset"
Lungehinde_5year_female_170_sygdomstekst                                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Keuhkopussi, naiset"
Bryst_5year_female_180_sygdomstekst                                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Rinta, naiset"
Livmoderhals_5year_female_190_sygdomstekst                                                     <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunkaula, naiset"
Livmoder_5year_female_200_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kohdunrunko, naiset"
Livmoder_uden_specifikation_5year_female_210_sygdomstekst                                      <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muu kohtusyöpä, naiset"
Aeggestok_aeggeleder_mv_5year_female_220_sygdomstekst                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Munasarjat, naiset"
Ovrige_kvindelige_konsorganer_5year_female_230_sygdomstekst                                    <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muut naisen sukuelimet, naiset"
Prostata_5year_female_240_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Eturauhanen, naiset"
Testikel_5year_female_250_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kives, naiset"
Penis_og_andre_mandlige_konsorganer_5year_female_260_sygdomstekst                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muut miehen sukuelimet, naiset"
Nyre_5year_female_270_sygdomstekst                                                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Munuainen, naiset"
Blaere_og_andre_urinveje_5year_female_280_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Virtsarakko ja muut virtsaelimet, naiset"
Modermaerkekraeft_hud_5year_female_290_sygdomstekst                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Ihomelanooma, naiset"
Anden_hud_ikke_modermaerke_5year_female_300_sygdomstekst                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Iho, ei melanooma, naiset"
Oje_5year_female_310_sygdomstekst                                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Silmä, naiset"
Hjerne_og_centralnervesystem_5year_female_320_sygdomstekst                                     <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Aivot ja hermosto, naiset"
Skjoldbruskkirtel_5year_female_330_sygdomstekst                                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kilpirauhanen, naiset"
Knogle_5year_female_340_sygdomstekst                                                           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Luu, naiset"
Bindevaev_5year_female_350_sygdomstekst                                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Pehmytkudos, naiset"
Non_Hodgkin_lymfom_5year_female_360_sygdomstekst                                               <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Non-Hodgkin -lymfooma, naiset"
Hodgkins_lymfom_5year_female_370_sygdomstekst                                                  <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Hodgkinin lymfooma, naiset"
Myelomatose_5year_female_380_sygdomstekst                                                      <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Myelooma, naiset"
Leukaemi_5year_female_400_sygdomstekst                                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, naiset"
Akut_lymfatisk_leukaemi_5year_female_401_sygdomstekst                                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen akuutti, naiset"
Kronisk_lymfatisk_leukaemi_5year_female_402_sygdomstekst                                       <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen krooninen, naiset"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403_sygdomstekst                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, lymfaattinen muu tai määrittämätön, naiset"
Akut_myeloid_leukaemi_5year_female_404_sygdomstekst                                            <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen akuutti, naiset"
Kronisk_myeloid_leukaemi_5year_female_405_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen krooninen, naiset"
Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406_sygdomstekst                          <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, myelooinen muu tai määrittämätön, naiset"
Leukaemi_uspecificerede_celler_5year_female_407_sygdomstekst                                   <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Leukemia, solutyyppi määrittelemätön, naiset"
Andre_specificerede_5year_female_410_sygdomstekst                                              <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Muu määritelty sijainti, naiset"
Ukendte_og_daarligt_definerede_5year_female_420_sygdomstekst                                   <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Tuntematon ja määrittelemätön sijainti, naiset"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970_sygdomstekst           <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, rinta- ja eturauhassyövät, naiset"
Alle_kraeftformer_5year_female_980_sygdomstekst                                                <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät, naiset"
Alle_kraeftformer_undtagen_anden_hud_5year_female_990_sygdomstekst                             <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Kaikki syövät paitsi ihon ei-melanoomat, naiset"
Laebe_mundhule_og_svaelg_5year_female_510_sygdomstekst                                         <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Suu ja nielu, naiset"
Tyk_og_endetarm_5year_female_520_sygdomstekst                                                  <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Paksu- ja peräsuoli, naiset"
Basocellulaere_carcinomer_5year_female_888_sygdomstekst                                        <-             "Parannus suhteellisessa 5-vuotiselossaolo-osuudessa, NORDCAN\n Basalioomat, naiset"





