Laebe_1year_male_10_sygdomstekst                                                               <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leppe, menn"
Mundhule_1year_male_20_sygdomstekst                                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tunge, menn"
Spytkirtel_1year_male_30_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Spyttkjertler, menn"
Oropharynx_1year_male_40_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Oropharynx, menn"
Nasopharynx_1year_male_41_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nasopharynx, menn"
Hypopharynx_1year_male_50_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hypopharynx, menn"
Pharynx_daarligt_defineret_1year_male_51_sygdomstekst                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Pharynx, dårlig definert, menn"
Spiseror_1year_male_60_sygdomstekst                                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Spiserør, menn"
Mave_1year_male_70_sygdomstekst                                                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Magesekk, menn"
Tyndtarm_1year_male_80_sygdomstekst                                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tynntarm, menn"
Tyktarm_1year_male_90_sygdomstekst                                                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tykktarm, menn"
Endetarm_og_anus_1year_male_100_sygdomstekst                                                   <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Endetarm og anus, menn"
Lever_1year_male_110_sygdomstekst                                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Lever, menn"
Galdeblaere_og_galdeveje_1year_male_120_sygdomstekst                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Galleblære og galleveier, menn"
Bugspytkirtel_1year_male_130_sygdomstekst                                                      <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Bukspyttkjertel, menn"
Naese_og_bihuler_1year_male_140_sygdomstekst                                                   <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nesehule, mellomøre, menn"
Strube_1year_male_150_sygdomstekst                                                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Strupehodet, menn"
Lunge_inkl_luftror_1year_male_160_sygdomstekst                                                 <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Lunge (inkl. luftrør og bronkier), menn"
Lungehinde_1year_male_170_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Brysthinne, menn"
Bryst_1year_male_180_sygdomstekst                                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Mamma, menn"
Livmoderhals_1year_male_190_sygdomstekst                                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmorhals, menn"
Livmoder_1year_male_200_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmorlegeme, menn"
Livmoder_uden_specifikation_1year_male_210_sygdomstekst                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmor, annet, menn"
Aeggestok_aeggeleder_mv_1year_male_220_sygdomstekst                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Eggstokk og eggleder, menn"
Ovrige_kvindelige_konsorganer_1year_male_230_sygdomstekst                                      <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre kvinnelige kjønnsorganer, menn"
Prostata_1year_male_240_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Prostata, menn"
Testikel_1year_male_250_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Testikkel, menn"
Penis_og_andre_mandlige_konsorganer_1year_male_260_sygdomstekst                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Penis og andre mannlige kjønnsorganer, menn"
Nyre_1year_male_270_sygdomstekst                                                               <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nyre, menn"
Blaere_og_andre_urinveje_1year_male_280_sygdomstekst                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Blære og urinrør, menn"
Modermaerkekraeft_hud_1year_male_290_sygdomstekst                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Føflekkreft i hud, menn"
Anden_hud_ikke_modermaerke_1year_male_300_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hud - andre krefttyper, menn"
Oje_1year_male_310_sygdomstekst                                                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Øye, menn"
Hjerne_og_centralnervesystem_1year_male_320_sygdomstekst                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hjerne og øvrige nervesystem, menn"
Skjoldbruskkirtel_1year_male_330_sygdomstekst                                                  <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Skjoldbruskkjertel, menn"
Knogle_1year_male_340_sygdomstekst                                                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Ben, menn"
Bindevaev_1year_male_350_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Bløtdeler, menn"
Non_Hodgkin_lymfom_1year_male_360_sygdomstekst                                                 <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Non-Hodgkin lymfom, menn"
Hodgkins_lymfom_1year_male_370_sygdomstekst                                                    <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hodgkin lymfom, menn"
Myelomatose_1year_male_380_sygdomstekst                                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Benmargskreft, menn"
Leukaemi_1year_male_400_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leukemi, menn"
Akut_lymfatisk_leukaemi_1year_male_401_sygdomstekst                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Akutt lymfatisk leukemi, menn"
Kronisk_lymfatisk_leukaemi_1year_male_402_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Kronisk lymfatisk leukemi, menn"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403_sygdomstekst                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte lymfatiske leukemier, menn"
Akut_myeloid_leukaemi_1year_male_404_sygdomstekst                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Akutt myelogen leukemi, menn"
Kronisk_myeloid_leukaemi_1year_male_405_sygdomstekst                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Kronisk myelogen leukemi, menn"
Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406_sygdomstekst                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte myelogene leukemier, menn"
Leukaemi_uspecificerede_celler_1year_male_407_sygdomstekst                                     <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leukemi uspesifisert, menn"
Andre_specificerede_1year_male_410_sygdomstekst                                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre spesifiserte, menn"
Ukendte_og_daarligt_definerede_1year_male_420_sygdomstekst                                     <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Ukjente og dårlig definerte, menn"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970_sygdomstekst             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer bortsett fra non-melanom hudkreft, brystkreft og prostatakreft, menn"
Alle_kraeftformer_1year_male_980_sygdomstekst                                                  <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer, menn"
Alle_kraeftformer_undtagen_anden_hud_1year_male_990_sygdomstekst                               <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer unntatt hudkreft annet enn føflekkreft, menn"
Laebe_mundhule_og_svaelg_1year_male_510_sygdomstekst                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leppe, munnhule og svelg, menn"
Tyk_og_endetarm_1year_male_520_sygdomstekst                                                    <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tykk- og endetarm, menn"
Basocellulaere_carcinomer_1year_male_888_sygdomstekst                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Basalcellekarsinomer, menn"
Laebe_1year_female_10_sygdomstekst                                                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leppe, kvinner"
Mundhule_1year_female_20_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tunge, kvinner"
Spytkirtel_1year_female_30_sygdomstekst                                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Spyttkjertler, kvinner"
Oropharynx_1year_female_40_sygdomstekst                                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Oropharynx, kvinner"
Nasopharynx_1year_female_41_sygdomstekst                                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nasopharynx, kvinner"
Hypopharynx_1year_female_50_sygdomstekst                                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hypopharynx, kvinner"
Pharynx_daarligt_defineret_1year_female_51_sygdomstekst                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Pharynx, dårlig definert, kvinner"
Spiseror_1year_female_60_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Spiserør, kvinner"
Mave_1year_female_70_sygdomstekst                                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Magesekk, kvinner"
Tyndtarm_1year_female_80_sygdomstekst                                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tynntarm, kvinner"
Tyktarm_1year_female_90_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tykktarm, kvinner"
Endetarm_og_anus_1year_female_100_sygdomstekst                                                 <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Endetarm og anus, kvinner"
Lever_1year_female_110_sygdomstekst                                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Lever, kvinner"
Galdeblaere_og_galdeveje_1year_female_120_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Galleblære og galleveier, kvinner"
Bugspytkirtel_1year_female_130_sygdomstekst                                                    <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Bukspyttkjertel, kvinner"
Naese_og_bihuler_1year_female_140_sygdomstekst                                                 <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nesehule, mellomøre, kvinner"
Strube_1year_female_150_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Strupehodet, kvinner"
Lunge_inkl_luftror_1year_female_160_sygdomstekst                                               <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Lunge (inkl. luftrør og bronkier), kvinner"
Lungehinde_1year_female_170_sygdomstekst                                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Brysthinne, kvinner"
Bryst_1year_female_180_sygdomstekst                                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Mamma, kvinner"
Livmoderhals_1year_female_190_sygdomstekst                                                     <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmorhals, kvinner"
Livmoder_1year_female_200_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmorlegeme, kvinner"
Livmoder_uden_specifikation_1year_female_210_sygdomstekst                                      <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Livmor, annet, kvinner"
Aeggestok_aeggeleder_mv_1year_female_220_sygdomstekst                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Eggstokk og eggleder, kvinner"
Ovrige_kvindelige_konsorganer_1year_female_230_sygdomstekst                                    <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre kvinnelige kjønnsorganer, kvinner"
Prostata_1year_female_240_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Prostata, kvinner"
Testikel_1year_female_250_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Testikkel, kvinner"
Penis_og_andre_mandlige_konsorganer_1year_female_260_sygdomstekst                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Penis og andre mannlige kjønnsorganer, kvinner"
Nyre_1year_female_270_sygdomstekst                                                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Nyre, kvinner"
Blaere_og_andre_urinveje_1year_female_280_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Blære og urinrør, kvinner"
Modermaerkekraeft_hud_1year_female_290_sygdomstekst                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Føflekkreft i hud, kvinner"
Anden_hud_ikke_modermaerke_1year_female_300_sygdomstekst                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hud - andre krefttyper, kvinner"
Oje_1year_female_310_sygdomstekst                                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Øye, kvinner"
Hjerne_og_centralnervesystem_1year_female_320_sygdomstekst                                     <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hjerne og øvrige nervesystem, kvinner"
Skjoldbruskkirtel_1year_female_330_sygdomstekst                                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Skjoldbruskkjertel, kvinner"
Knogle_1year_female_340_sygdomstekst                                                           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Ben, kvinner"
Bindevaev_1year_female_350_sygdomstekst                                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Bløtdeler, kvinner"
Non_Hodgkin_lymfom_1year_female_360_sygdomstekst                                               <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Non-Hodgkin lymfom, kvinner"
Hodgkins_lymfom_1year_female_370_sygdomstekst                                                  <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Hodgkin lymfom, kvinner"
Myelomatose_1year_female_380_sygdomstekst                                                      <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Benmargskreft, kvinner"
Leukaemi_1year_female_400_sygdomstekst                                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leukemi, kvinner"
Akut_lymfatisk_leukaemi_1year_female_401_sygdomstekst                                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Akutt lymfatisk leukemi, kvinner"
Kronisk_lymfatisk_leukaemi_1year_female_402_sygdomstekst                                       <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Kronisk lymfatisk leukemi, kvinner"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403_sygdomstekst                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte lymfatiske leukemier, kvinner"
Akut_myeloid_leukaemi_1year_female_404_sygdomstekst                                            <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Akutt myelogen leukemi, kvinner"
Kronisk_myeloid_leukaemi_1year_female_405_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Kronisk myelogen leukemi, kvinner"
Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406_sygdomstekst                          <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte myelogene leukemier, kvinner"
Leukaemi_uspecificerede_celler_1year_female_407_sygdomstekst                                   <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leukemi uspesifisert, kvinner"
Andre_specificerede_1year_female_410_sygdomstekst                                              <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Andre spesifiserte, kvinner"
Ukendte_og_daarligt_definerede_1year_female_420_sygdomstekst                                   <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Ukjente og dårlig definerte, kvinner"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970_sygdomstekst           <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer bortsett fra non-melanom hudkreft, brystkreft og prostatakreft, kvinner"
Alle_kraeftformer_1year_female_980_sygdomstekst                                                <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer, kvinner"
Alle_kraeftformer_undtagen_anden_hud_1year_female_990_sygdomstekst                             <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer unntatt hudkreft annet enn føflekkreft, kvinner"
Laebe_mundhule_og_svaelg_1year_female_510_sygdomstekst                                         <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Leppe, munnhule og svelg, kvinner"
Tyk_og_endetarm_1year_female_520_sygdomstekst                                                  <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Tykk- og endetarm, kvinner"
Basocellulaere_carcinomer_1year_female_888_sygdomstekst                                        <-              "Forbedring i 1-års relativ kreftoverlevelse, NORDCAN\n Basalcellekarsinomer, kvinner"
Laebe_5year_male_10_sygdomstekst                                                               <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leppe, menn"
Mundhule_5year_male_20_sygdomstekst                                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tunge, menn"
Spytkirtel_5year_male_30_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Spyttkjertler, menn"
Oropharynx_5year_male_40_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Oropharynx, menn"
Nasopharynx_5year_male_41_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nasopharynx, menn"
Hypopharynx_5year_male_50_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hypopharynx, menn"
Pharynx_daarligt_defineret_5year_male_51_sygdomstekst                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Pharynx, dårlig definert, menn"
Spiseror_5year_male_60_sygdomstekst                                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Spiserør, menn"
Mave_5year_male_70_sygdomstekst                                                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Magesekk, menn"
Tyndtarm_5year_male_80_sygdomstekst                                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tynntarm, menn"
Tyktarm_5year_male_90_sygdomstekst                                                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tykktarm, menn"
Endetarm_og_anus_5year_male_100_sygdomstekst                                                   <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Endetarm og anus, menn"
Lever_5year_male_110_sygdomstekst                                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Lever, menn"
Galdeblaere_og_galdeveje_5year_male_120_sygdomstekst                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Galleblære og galleveier, menn"
Bugspytkirtel_5year_male_130_sygdomstekst                                                      <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Bukspyttkjertel, menn"
Naese_og_bihuler_5year_male_140_sygdomstekst                                                   <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nesehule, mellomøre, menn"
Strube_5year_male_150_sygdomstekst                                                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Strupehodet, menn"
Lunge_inkl_luftror_5year_male_160_sygdomstekst                                                 <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Lunge (inkl. luftrør og bronkier), menn"
Lungehinde_5year_male_170_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Brysthinne, menn"
Bryst_5year_male_180_sygdomstekst                                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Mamma, menn"
Livmoderhals_5year_male_190_sygdomstekst                                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmorhals, menn"
Livmoder_5year_male_200_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmorlegeme, menn"
Livmoder_uden_specifikation_5year_male_210_sygdomstekst                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmor, annet, menn"
Aeggestok_aeggeleder_mv_5year_male_220_sygdomstekst                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Eggstokk og eggleder, menn"
Ovrige_kvindelige_konsorganer_5year_male_230_sygdomstekst                                      <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre kvinnelige kjønnsorganer, menn"
Prostata_5year_male_240_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Prostata, menn"
Testikel_5year_male_250_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Testikkel, menn"
Penis_og_andre_mandlige_konsorganer_5year_male_260_sygdomstekst                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Penis og andre mannlige kjønnsorganer, menn"
Nyre_5year_male_270_sygdomstekst                                                               <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nyre, menn"
Blaere_og_andre_urinveje_5year_male_280_sygdomstekst                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Blære og urinrør, menn"
Modermaerkekraeft_hud_5year_male_290_sygdomstekst                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Føflekkreft i hud, menn"
Anden_hud_ikke_modermaerke_5year_male_300_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hud - andre krefttyper, menn"
Oje_5year_male_310_sygdomstekst                                                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Øye, menn"
Hjerne_og_centralnervesystem_5year_male_320_sygdomstekst                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hjerne og øvrige nervesystem, menn"
Skjoldbruskkirtel_5year_male_330_sygdomstekst                                                  <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Skjoldbruskkjertel, menn"
Knogle_5year_male_340_sygdomstekst                                                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Ben, menn"
Bindevaev_5year_male_350_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Bløtdeler, menn"
Non_Hodgkin_lymfom_5year_male_360_sygdomstekst                                                 <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Non-Hodgkin lymfom, menn"
Hodgkins_lymfom_5year_male_370_sygdomstekst                                                    <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hodgkin lymfom, menn"
Myelomatose_5year_male_380_sygdomstekst                                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Benmargskreft, menn"
Leukaemi_5year_male_400_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leukemi, menn"
Akut_lymfatisk_leukaemi_5year_male_401_sygdomstekst                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Akutt lymfatisk leukemi, menn"
Kronisk_lymfatisk_leukaemi_5year_male_402_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Kronisk lymfatisk leukemi, menn"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403_sygdomstekst                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte lymfatiske leukemier, menn"
Akut_myeloid_leukaemi_5year_male_404_sygdomstekst                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Akutt myelogen leukemi, menn"
Kronisk_myeloid_leukaemi_5year_male_405_sygdomstekst                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Kronisk myelogen leukemi, menn"
Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406_sygdomstekst                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte myelogene leukemier, menn"
Leukaemi_uspecificerede_celler_5year_male_407_sygdomstekst                                     <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leukemi uspesifisert, menn"
Andre_specificerede_5year_male_410_sygdomstekst                                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre spesifiserte, menn"
Ukendte_og_daarligt_definerede_5year_male_420_sygdomstekst                                     <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Ukjente og dårlig definerte, menn"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970_sygdomstekst             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer bortsett fra non-melanom hudkreft, brystkreft og prostatakreft, menn"
Alle_kraeftformer_5year_male_980_sygdomstekst                                                  <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer, menn"
Alle_kraeftformer_undtagen_anden_hud_5year_male_990_sygdomstekst                               <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer unntatt hudkreft annet enn føflekkreft, menn"
Laebe_mundhule_og_svaelg_5year_male_510_sygdomstekst                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leppe, munnhule og svelg, menn"
Tyk_og_endetarm_5year_male_520_sygdomstekst                                                    <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tykk- og endetarm, menn"
Basocellulaere_carcinomer_5year_male_888_sygdomstekst                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Basalcellekarsinomer, menn"
Laebe_5year_female_10_sygdomstekst                                                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leppe, kvinner"
Mundhule_5year_female_20_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tunge, kvinner"
Spytkirtel_5year_female_30_sygdomstekst                                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Spyttkjertler, kvinner"
Oropharynx_5year_female_40_sygdomstekst                                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Oropharynx, kvinner"
Nasopharynx_5year_female_41_sygdomstekst                                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nasopharynx, kvinner"
Hypopharynx_5year_female_50_sygdomstekst                                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hypopharynx, kvinner"
Pharynx_daarligt_defineret_5year_female_51_sygdomstekst                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Pharynx, dårlig definert, kvinner"
Spiseror_5year_female_60_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Spiserør, kvinner"
Mave_5year_female_70_sygdomstekst                                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Magesekk, kvinner"
Tyndtarm_5year_female_80_sygdomstekst                                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tynntarm, kvinner"
Tyktarm_5year_female_90_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tykktarm, kvinner"
Endetarm_og_anus_5year_female_100_sygdomstekst                                                 <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Endetarm og anus, kvinner"
Lever_5year_female_110_sygdomstekst                                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Lever, kvinner"
Galdeblaere_og_galdeveje_5year_female_120_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Galleblære og galleveier, kvinner"
Bugspytkirtel_5year_female_130_sygdomstekst                                                    <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Bukspyttkjertel, kvinner"
Naese_og_bihuler_5year_female_140_sygdomstekst                                                 <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nesehule, mellomøre, kvinner"
Strube_5year_female_150_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Strupehodet, kvinner"
Lunge_inkl_luftror_5year_female_160_sygdomstekst                                               <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Lunge (inkl. luftrør og bronkier), kvinner"
Lungehinde_5year_female_170_sygdomstekst                                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Brysthinne, kvinner"
Bryst_5year_female_180_sygdomstekst                                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Mamma, kvinner"
Livmoderhals_5year_female_190_sygdomstekst                                                     <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmorhals, kvinner"
Livmoder_5year_female_200_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmorlegeme, kvinner"
Livmoder_uden_specifikation_5year_female_210_sygdomstekst                                      <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Livmor, annet, kvinner"
Aeggestok_aeggeleder_mv_5year_female_220_sygdomstekst                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Eggstokk og eggleder, kvinner"
Ovrige_kvindelige_konsorganer_5year_female_230_sygdomstekst                                    <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre kvinnelige kjønnsorganer, kvinner"
Prostata_5year_female_240_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Prostata, kvinner"
Testikel_5year_female_250_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Testikkel, kvinner"
Penis_og_andre_mandlige_konsorganer_5year_female_260_sygdomstekst                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Penis og andre mannlige kjønnsorganer, kvinner"
Nyre_5year_female_270_sygdomstekst                                                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Nyre, kvinner"
Blaere_og_andre_urinveje_5year_female_280_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Blære og urinrør, kvinner"
Modermaerkekraeft_hud_5year_female_290_sygdomstekst                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Føflekkreft i hud, kvinner"
Anden_hud_ikke_modermaerke_5year_female_300_sygdomstekst                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hud - andre krefttyper, kvinner"
Oje_5year_female_310_sygdomstekst                                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Øye, kvinner"
Hjerne_og_centralnervesystem_5year_female_320_sygdomstekst                                     <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hjerne og øvrige nervesystem, kvinner"
Skjoldbruskkirtel_5year_female_330_sygdomstekst                                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Skjoldbruskkjertel, kvinner"
Knogle_5year_female_340_sygdomstekst                                                           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Ben, kvinner"
Bindevaev_5year_female_350_sygdomstekst                                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Bløtdeler, kvinner"
Non_Hodgkin_lymfom_5year_female_360_sygdomstekst                                               <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Non-Hodgkin lymfom, kvinner"
Hodgkins_lymfom_5year_female_370_sygdomstekst                                                  <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Hodgkin lymfom, kvinner"
Myelomatose_5year_female_380_sygdomstekst                                                      <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Benmargskreft, kvinner"
Leukaemi_5year_female_400_sygdomstekst                                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leukemi, kvinner"
Akut_lymfatisk_leukaemi_5year_female_401_sygdomstekst                                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Akutt lymfatisk leukemi, kvinner"
Kronisk_lymfatisk_leukaemi_5year_female_402_sygdomstekst                                       <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Kronisk lymfatisk leukemi, kvinner"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403_sygdomstekst                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte lymfatiske leukemier, kvinner"
Akut_myeloid_leukaemi_5year_female_404_sygdomstekst                                            <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Akutt myelogen leukemi, kvinner"
Kronisk_myeloid_leukaemi_5year_female_405_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Kronisk myelogen leukemi, kvinner"
Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406_sygdomstekst                          <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre og uspesifiserte myelogene leukemier, kvinner"
Leukaemi_uspecificerede_celler_5year_female_407_sygdomstekst                                   <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leukemi uspesifisert, kvinner"
Andre_specificerede_5year_female_410_sygdomstekst                                              <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Andre spesifiserte, kvinner"
Ukendte_og_daarligt_definerede_5year_female_420_sygdomstekst                                   <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Ukjente og dårlig definerte, kvinner"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970_sygdomstekst           <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer bortsett fra non-melanom hudkreft, brystkreft og prostatakreft, kvinner"
Alle_kraeftformer_5year_female_980_sygdomstekst                                                <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer, kvinner"
Alle_kraeftformer_undtagen_anden_hud_5year_female_990_sygdomstekst                             <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Alle kreftformer unntatt hudkreft annet enn føflekkreft, kvinner"
Laebe_mundhule_og_svaelg_5year_female_510_sygdomstekst                                         <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Leppe, munnhule og svelg, kvinner"
Tyk_og_endetarm_5year_female_520_sygdomstekst                                                  <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Tykk- og endetarm, kvinner"
Basocellulaere_carcinomer_5year_female_888_sygdomstekst                                        <-              "Forbedring i 5-års relativ kreftoverlevelse, NORDCAN\n Basalcellekarsinomer, kvinner"









