




# entity --------------------------------------------------------------------




entity <-
c(
"10",
"20",
"30",
"40",
"41",
"50",
"51",
"60",
"70",
"80",
"90",
"100",
"110",
"120",
"130",
"140",
"150",
"160",
"170",
"180",
"190",
"200",
"210",
"220",
"230",
"240",
"250",
"260",
"270",
"280",
"290",
"300",
"310",
"320",
"330",
"340",
"350",
"360",
"370",
"380",
"400",
"401",
"402",
"403",
"404",
"405",
"406",
"407",
"410",
"420",
"970",
"980",
"990",
"510",
"520",
"888"  )


# jacques -----------------------------------------------------------------



jacques <-   c(
  "10",
"20",
"30",
"40",
"50",
"60",
"70",
"80",
"90",
"100",
"110",
"120",
"130",
"140",
"150",
"160",
"170",
"180",
"190",
"200",
"212",
"222",
"232",
"242",
"252",
"261",
"271",
"281",
"290",
"300",
"310",
"320",
"330",
"340",
"350",
"360",
"370",
"380",
"390",
"400",
"410",
"420",
"430",
"440",
"450",
"460",
"470",
"480",
"490",
"500",
"530",    # This has been renamed from 970 to 530 (only in Jacques names, the english names shall remain the same ) 
"510",
"520",
"540",
"550",
"888"  )


# english filenames -------------------------------------------------------






english_filenames <- c("Lip_men_1year_male_10",
                     "Oral_cavity_men_1year_male_20",
                     "Salivary_glands_men_1year_male_30",
                     "Oropharynx_men_1year_male_40",
                     "Nasopharynx_men_1year_male_41",
                     "Hypopharynx_men_1year_male_50",
                     "Pharynx_illdefined_men_1year_male_51",
                     "Oesophagus_men_1year_male_60",
                     "Stomach_men_1year_male_70",
                     "Small_intestine_men_1year_male_80",
                     "Colon_men_1year_male_90",
                     "Rectum_and_anus_men_1year_male_100",
                     "Liver_men_1year_male_110",
                     "Gallbladder_men_1year_male_120",
                     "Pancreas_men_1year_male_130",
                     "Nose_sinuses_men_1year_male_140",
                     "Larynx_men_1year_male_150",
                     "Lung_men_1year_male_160",
                     "Pleura_men_1year_male_170",
                     "Breast_men_1year_male_180",
                     "Cervix_uteri_men_1year_male_190",
                     "Corpus_uteri_men_1year_male_200",
                     "Uterus_other_men_1year_male_210",
                     "Ovary_etc_men_1year_male_220",
                     "Other_female_genital_organs_men_1year_male_230",
                     "Prostate_men_1year_male_240",
                     "Testis_men_1year_male_250",
                     "Penis_etc_men_1year_male_260",
                     "Kidney_men_1year_male_270",
                     "Bladder_etc_men_1year_male_280",
                     "Melanoma_of_skin_men_1year_male_290",
                     "Skin_nonmelanoma_men_1year_male_300",
                     "Eye_men_1year_male_310",
                     "Brain_central_nervous_system_men_1year_male_320",
                     "Thyroid_men_1year_male_330",
                     "Bone_men_1year_male_340",
                     "Soft_tissues_men_1year_male_350",
                     "NonHodgkin_lymphoma_men_1year_male_360",
                     "Hodgkin_lymphoma_men_1year_male_370",
                     "Multiple_myeloma_men_1year_male_380",
                     "Leukaemia_men_1year_male_400",
                     "Acute_lymphatic_leukaemia_men_1year_male_401",
                     "Chronic_lymphatic_leukaemia_men_1year_male_402",
                     "Other_and_unspecified_lymphatic_leukaemia_men_1year_male_403",
                     "Acute_myeloid_leukaemia_men_1year_male_404",
                     "Chronic_myeloid_leukaemia_men_1year_male_405",
                     "Other_and_unspecified_myeloid_leukaemia_men_1year_male_406",
                     "Leukaemia_cell_unspecified_men_1year_male_407",
                     "Other_specified_cancers_men_1year_male_410",
                     "Unknown_and_illdefined_men_1year_male_420",
                     "All_sites_but_nonmelanoma_skin_breast_and_prostate_cancer_men_1year_male_970",
                     "All_sites_men_1year_male_980",
                     "All_sites_but_nonmelanoma_skin_cancer_men_1year_male_990",
                     "Lip_oral_cavity_and_pharynx_men_1year_male_510",
                     "Colorectal_men_1year_male_520",
                     "Basocellular_carcinomas_men_1year_male_888",
                     "Lip_women_1year_female_10",
                     "Oral_cavity_women_1year_female_20",
                     "Salivary_glands_women_1year_female_30",
                     "Oropharynx_women_1year_female_40",
                     "Nasopharynx_women_1year_female_41",
                     "Hypopharynx_women_1year_female_50",
                     "Pharynx_illdefined_women_1year_female_51",
                     "Oesophagus_women_1year_female_60",
                     "Stomach_women_1year_female_70",
                     "Small_intestine_women_1year_female_80",
                     "Colon_women_1year_female_90",
                     "Rectum_and_anus_women_1year_female_100",
                     "Liver_women_1year_female_110",
                     "Gallbladder_women_1year_female_120",
                     "Pancreas_women_1year_female_130",
                     "Nose_sinuses_women_1year_female_140",
                     "Larynx_women_1year_female_150",
                     "Lung_women_1year_female_160",
                     "Pleura_women_1year_female_170",
                     "Breast_women_1year_female_180",
                     "Cervix_uteri_women_1year_female_190",
                     "Corpus_uteri_women_1year_female_200",
                     "Uterus_other_women_1year_female_210",
                     "Ovary_etc_women_1year_female_220",
                     "Other_female_genital_organs_women_1year_female_230",
                     "Prostate_women_1year_female_240",
                     "Testis_women_1year_female_250",
                     "Penis_etc_women_1year_female_260",
                     "Kidney_women_1year_female_270",
                     "Bladder_etc_women_1year_female_280",
                     "Melanoma_of_skin_women_1year_female_290",
                     "Skin_nonmelanoma_women_1year_female_300",
                     "Eye_women_1year_female_310",
                     "Brain_central_nervous_system_women_1year_female_320",
                     "Thyroid_women_1year_female_330",
                     "Bone_women_1year_female_340",
                     "Soft_tissues_women_1year_female_350",
                     "NonHodgkin_lymphoma_women_1year_female_360",
                     "Hodgkin_lymphoma_women_1year_female_370",
                     "Multiple_myeloma_women_1year_female_380",
                     "Leukaemia_women_1year_female_400",
                     "Acute_lymphatic_leukaemia_women_1year_female_401",
                     "Chronic_lymphatic_leukaemia_women_1year_female_402",
                     "Other_and_unspecified_lymphatic_leukaemia_women_1year_female_403",
                     "Acute_myeloid_leukaemia_women_1year_female_404",
                     "Chronic_myeloid_leukaemia_women_1year_female_405",
                     "Other_and_unspecified_myeloid_leukaemia_women_1year_female_406",
                     "Leukaemia_cell_unspecified_women_1year_female_407",
                     "Other_specified_cancers_women_1year_female_410",
                     "Unknown_and_illdefined_women_1year_female_420",
                     "All_sites_but_nonmelanoma_skin_breast_and_prostate_cancer_women_1year_female_970",
                     "All_sites_women_1year_female_980",
                     "All_sites_but_nonmelanoma_skin_cancer_women_1year_female_990",
                     "Lip_oral_cavity_and_pharynx_women_1year_female_510",
                     "Colorectal_women_1year_female_520",
                     "Basocellular_carcinomas_women_1year_female_888",
                     "Lip_men_5year_male_10",
                     "Oral_cavity_men_5year_male_20",
                     "Salivary_glands_men_5year_male_30",
                     "Oropharynx_men_5year_male_40",
                     "Nasopharynx_men_5year_male_41",
                     "Hypopharynx_men_5year_male_50",
                     "Pharynx_illdefined_men_5year_male_51",
                     "Oesophagus_men_5year_male_60",
                     "Stomach_men_5year_male_70",
                     "Small_intestine_men_5year_male_80",
                     "Colon_men_5year_male_90",
                     "Rectum_and_anus_men_5year_male_100",
                     "Liver_men_5year_male_110",
                     "Gallbladder_men_5year_male_120",
                     "Pancreas_men_5year_male_130",
                     "Nose_sinuses_men_5year_male_140",
                     "Larynx_men_5year_male_150",
                     "Lung_men_5year_male_160",
                     "Pleura_men_5year_male_170",
                     "Breast_men_5year_male_180",
                     "Cervix_uteri_men_5year_male_190",
                     "Corpus_uteri_men_5year_male_200",
                     "Uterus_other_men_5year_male_210",
                     "Ovary_etc_men_5year_male_220",
                     "Other_female_genital_organs_men_5year_male_230",
                     "Prostate_men_5year_male_240",
                     "Testis_men_5year_male_250",
                     "Penis_etc_men_5year_male_260",
                     "Kidney_men_5year_male_270",
                     "Bladder_etc_men_5year_male_280",
                     "Melanoma_of_skin_men_5year_male_290",
                     "Skin_nonmelanoma_men_5year_male_300",
                     "Eye_men_5year_male_310",
                     "Brain_central_nervous_system_men_5year_male_320",
                     "Thyroid_men_5year_male_330",
                     "Bone_men_5year_male_340",
                     "Soft_tissues_men_5year_male_350",
                     "NonHodgkin_lymphoma_men_5year_male_360",
                     "Hodgkin_lymphoma_men_5year_male_370",
                     "Multiple_myeloma_men_5year_male_380",
                     "Leukaemia_men_5year_male_400",
                     "Acute_lymphatic_leukaemia_men_5year_male_401",
                     "Chronic_lymphatic_leukaemia_men_5year_male_402",
                     "Other_and_unspecified_lymphatic_leukaemia_men_5year_male_403",
                     "Acute_myeloid_leukaemia_men_5year_male_404",
                     "Chronic_myeloid_leukaemia_men_5year_male_405",
                     "Other_and_unspecified_myeloid_leukaemia_men_5year_male_406",
                     "Leukaemia_cell_unspecified_men_5year_male_407",
                     "Other_specified_cancers_men_5year_male_410",
                     "Unknown_and_illdefined_men_5year_male_420",
                     "All_sites_but_nonmelanoma_skin_breast_and_prostate_cancer_men_5year_male_970",
                     "All_sites_men_5year_male_980",
                     "All_sites_but_nonmelanoma_skin_cancer_men_5year_male_990",
                     "Lip_oral_cavity_and_pharynx_men_5year_male_510",
                     "Colorectal_men_5year_male_520",
                     "Basocellular_carcinomas_men_5year_male_888",
                     "Lip_women_5year_female_10",
                     "Oral_cavity_women_5year_female_20",
                     "Salivary_glands_women_5year_female_30",
                     "Oropharynx_women_5year_female_40",
                     "Nasopharynx_women_5year_female_41",
                     "Hypopharynx_women_5year_female_50",
                     "Pharynx_illdefined_women_5year_female_51",
                     "Oesophagus_women_5year_female_60",
                     "Stomach_women_5year_female_70",
                     "Small_intestine_women_5year_female_80",
                     "Colon_women_5year_female_90",
                     "Rectum_and_anus_women_5year_female_100",
                     "Liver_women_5year_female_110",
                     "Gallbladder_women_5year_female_120",
                     "Pancreas_women_5year_female_130",
                     "Nose_sinuses_women_5year_female_140",
                     "Larynx_women_5year_female_150",
                     "Lung_women_5year_female_160",
                     "Pleura_women_5year_female_170",
                     "Breast_women_5year_female_180",
                     "Cervix_uteri_women_5year_female_190",
                     "Corpus_uteri_women_5year_female_200",
                     "Uterus_other_women_5year_female_210",
                     "Ovary_etc_women_5year_female_220",
                     "Other_female_genital_organs_women_5year_female_230",
                     "Prostate_women_5year_female_240",
                     "Testis_women_5year_female_250",
                     "Penis_etc_women_5year_female_260",
                     "Kidney_women_5year_female_270",
                     "Bladder_etc_women_5year_female_280",
                     "Melanoma_of_skin_women_5year_female_290",
                     "Skin_nonmelanoma_women_5year_female_300",
                     "Eye_women_5year_female_310",
                     "Brain_central_nervous_system_women_5year_female_320",
                     "Thyroid_women_5year_female_330",
                     "Bone_women_5year_female_340",
                     "Soft_tissues_women_5year_female_350",
                     "NonHodgkin_lymphoma_women_5year_female_360",
                     "Hodgkin_lymphoma_women_5year_female_370",
                     "Multiple_myeloma_women_5year_female_380",
                     "Leukaemia_women_5year_female_400",
                     "Acute_lymphatic_leukaemia_women_5year_female_401",
                     "Chronic_lymphatic_leukaemia_women_5year_female_402",
                     "Other_and_unspecified_lymphatic_leukaemia_women_5year_female_403",
                     "Acute_myeloid_leukaemia_women_5year_female_404",
                     "Chronic_myeloid_leukaemia_women_5year_female_405",
                     "Other_and_unspecified_myeloid_leukaemia_women_5year_female_406",
                     "Leukaemia_cell_unspecified_women_5year_female_407",
                     "Other_specified_cancers_women_5year_female_410",
                     "Unknown_and_illdefined_women_5year_female_420",
                     "All_sites_but_nonmelanoma_skin_breast_and_prostate_cancer_women_5year_female_970",
                     "All_sites_women_5year_female_980",
                     "All_sites_but_nonmelanoma_skin_cancer_women_5year_female_990",
                     "Lip_oral_cavity_and_pharynx_women_5year_female_510",
                     "Colorectal_women_5year_female_520",
                     "Basocellular_carcinomas_women_5year_female_888" ) 


# dataframe laves ---------------------------------------------------------



jacques_names <- data.frame( long = english_filenames,
                  "entitet" = entity, 
                  "english" = 0,
                  "danish"  = 1,
                  "finnish" = 2,
                  "icelandic" = 3,
                  "norwegian" = 4,
                  "swedish"   = 5,
                  "dash"      = "-",
                  "jac" = jacques, 
                  "underscore" = "_",
                  "gender" = rep( 1:2, times = 2, each = 56 ),
                  "underscore2" = "_",
                  "follow_up" =  rep( c(1,5), times = 1, each = 112),
                  "comma"     =  c( rep(",", times = 223), "" ),
                  "quote"     =  "\""  )


jacques_names$long_png   <-   paste0( jacques_names$long, ".png" )

jacques_names$english_name_jac                <- paste0(  jacques_names$english,    jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up,      ".png"       )
jacques_names$danish_name_jac                 <- paste0(  jacques_names$danish,     jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up,      ".png"       )
jacques_names$finnish_name_jac                <- paste0(  jacques_names$finnish,    jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up,      ".png"       )
jacques_names$icelandic_name_jac              <- paste0(  jacques_names$icelandic,  jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up,      ".png"       )
jacques_names$norwegian_name_jac              <- paste0(  jacques_names$norwegian,  jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up, ".png"        )
jacques_names$swedish_name_jac                <- paste0(  jacques_names$swedish,    jacques_names$dash, jacques_names$jac, jacques_names$underscore, jacques_names$gender, jacques_names$underscore2, jacques_names$follow_up, ".png"         )










