---
output:
  word_document: default
  html_document:
    keep_md: yes
---



Plots eksporteres til word format, men vi er interesserede i at have plotsne for sig i én folder med engelske og en anden folder med danske plots. English sættes til TRUE/FALSE alt efter
om man vil, english skal vist slettes.





```{r,echo=FALSE}
# chunk som bestemmer hvilket sprog plots skal være på. Idet dette skript køres af hovedskriptet, skal denne chunk være
# udkommenteret, fordi sprogkoden skal styres fra hovedskriptet. 

# sprog_kode <- 1  # english
# sprog_kode <- 2  # danish
# sprog_kode <- 3  # finnish
# sprog_kode <- 4  # icelandic
# sprog_kode <- 5  # norwegian
# sprog_kode <- 6  # swedish


```




```{r,libraries, echo=FALSE, warning=FALSE,message=FALSE}



opts_chunk$set(warning=FALSE, echo=FALSE, message = FALSE, fig.width = 6, fig.height = 4.5, dpi = 600, dev = c("png"), cache = FALSE)


setwd( home_library)
base::source( file = "data hentes.R",     encoding = "UTF-8"    )


setwd( home_library)
base::source( file = "function 3 pile.R", encoding = "UTF-8"    )


setwd( disease_text ) 
if (sprog_kode==1) {
  
base::source( file = "english disease text.r", encoding = "UTF-8" ) 
  
}else if (sprog_kode==2) {
  
base::source( file = "danish disease text.r", encoding = "UTF-8" ) 
} else if (sprog_kode==3) {
  
base::source( file = "finnish disease text.r" ) 
  } else if (sprog_kode==4) {
  
base::source( file = "icelandic disease text.r" ) 
  } else if (sprog_kode==5) {
  
base::source( file = "norwegian disease text.r" ) 
  } else if (sprog_kode==6) {
  
base::source( file = "swedish disease text.r" )   }



```


Der kører fire chunks:
male1year
female1year
male5year
female5year


```{r male1year,echo=FALSE,eval=TRUE }



## arrow basic
rightarrow1  <-  0.997
rightarrow2  <-  .997
leftarrow1  <-   1.004  
leftarrow2  <-   1.004

pilefunktion( Laebe_1year_male_10                                                          ,       Laebe_1year_male_10_sygdomstekst                                                          , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Mundhule_1year_male_20                                                       ,       Mundhule_1year_male_20_sygdomstekst                                                       , sprog_kode )    


#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS


## arrow basic
rightarrow1  <-  .995
rightarrow2  <-  .995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Spytkirtel_1year_male_30                                                     ,       Spytkirtel_1year_male_30_sygdomstekst                                                     , sprog_kode )    


#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Oropharynx_1year_male_40                                                     ,       Oropharynx_1year_male_40_sygdomstekst                                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nasopharynx_1year_male_41                                                    ,       Nasopharynx_1year_male_41_sygdomstekst                                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hypopharynx_1year_male_50                                                    ,       Hypopharynx_1year_male_50_sygdomstekst                                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Pharynx_daarligt_defineret_1year_male_51                                     ,       Pharynx_daarligt_defineret_1year_male_51_sygdomstekst                                     , sprog_kode )    

## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Spiseror_1year_male_60                                                       ,       Spiseror_1year_male_60_sygdomstekst                                                       , sprog_kode )    


## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.013  
leftarrow2  <-   1.013


pilefunktion( Mave_1year_male_70                                                           ,       Mave_1year_male_70_sygdomstekst                                                           , sprog_kode )    



## arrow basic
rightarrow1  <-  0.983
rightarrow2  <-  0.983
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyndtarm_1year_male_80                                                       ,       Tyndtarm_1year_male_80_sygdomstekst                                                       , sprog_kode )    




## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyktarm_1year_male_90                                                        ,       Tyktarm_1year_male_90_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Endetarm_og_anus_1year_male_100                                              ,       Endetarm_og_anus_1year_male_100_sygdomstekst                                              , sprog_kode )    


## arrow basic
rightarrow1  <-  0.967
rightarrow2  <-  0.98
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lever_1year_male_110                                                         ,       Lever_1year_male_110_sygdomstekst                                                         , sprog_kode )    




## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Galdeblaere_og_galdeveje_1year_male_120                                      ,       Galdeblaere_og_galdeveje_1year_male_120_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.970
rightarrow2  <-  0.976
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bugspytkirtel_1year_male_130                                                 ,       Bugspytkirtel_1year_male_130_sygdomstekst                                                 , sprog_kode )    



## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.006  
leftarrow2  <-   1.006


pilefunktion( Naese_og_bihuler_1year_male_140                                              ,       Naese_og_bihuler_1year_male_140_sygdomstekst                                              , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.0
leftarrow2  <-   1.0


pilefunktion( Strube_1year_male_150                                                        ,       Strube_1year_male_150_sygdomstekst                                                        , sprog_kode )    




## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.020  
leftarrow2  <-   1.020


pilefunktion( Lunge_inkl_luftror_1year_male_160                                            ,       Lunge_inkl_luftror_1year_male_160_sygdomstekst                                            , sprog_kode )    


## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lungehinde_1year_male_170                                                    ,       Lungehinde_1year_male_170_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bryst_1year_male_180                                                         ,       Bryst_1year_male_180_sygdomstekst                                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoderhals_1year_male_190                                                  ,       Livmoderhals_1year_male_190_sygdomstekst                                                  , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_1year_male_200                                                      ,       Livmoder_1year_male_200_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_uden_specifikation_1year_male_210                                   ,       Livmoder_uden_specifikation_1year_male_210_sygdomstekst                                   , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Aeggestok_aeggeleder_mv_1year_male_220                                       ,       Aeggestok_aeggeleder_mv_1year_male_220_sygdomstekst                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ovrige_kvindelige_konsorganer_1year_male_230                                 ,       Ovrige_kvindelige_konsorganer_1year_male_230_sygdomstekst                                 , sprog_kode )    

## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Prostata_1year_male_240                                                      ,       Prostata_1year_male_240_sygdomstekst                                                      , sprog_kode )    

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Testikel_1year_male_250                                                      ,       Testikel_1year_male_250_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Penis_og_andre_mandlige_konsorganer_1year_male_260                           ,       Penis_og_andre_mandlige_konsorganer_1year_male_260_sygdomstekst                           , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nyre_1year_male_270                                                          ,       Nyre_1year_male_270_sygdomstekst                                                          , sprog_kode )    


## arrow basic
rightarrow1  <-  0.9967
rightarrow2  <-  0.9967
leftarrow1  <-   1.0  
leftarrow2  <-   1.0

pilefunktion( Blaere_og_andre_urinveje_1year_male_280                                      ,       Blaere_og_andre_urinveje_1year_male_280_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01

pilefunktion( Modermaerkekraeft_hud_1year_male_290                                         ,       Modermaerkekraeft_hud_1year_male_290_sygdomstekst                                         , sprog_kode )    


## arrow basic
rightarrow1  <-  0.997
rightarrow2  <-  0.997
leftarrow1  <-   1.003  
leftarrow2  <-   1.003


pilefunktion( Anden_hud_ikke_modermaerke_1year_male_300                                    ,       Anden_hud_ikke_modermaerke_1year_male_300_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Oje_1year_male_310                                                           ,       Oje_1year_male_310_sygdomstekst                                                           , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hjerne_og_centralnervesystem_1year_male_320                                  ,       Hjerne_og_centralnervesystem_1year_male_320_sygdomstekst                                  , sprog_kode )    

## arrow basic
rightarrow1  <-  0.992
rightarrow2  <-  0.992
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Skjoldbruskkirtel_1year_male_330                                             ,       Skjoldbruskkirtel_1year_male_330_sygdomstekst                                             , sprog_kode )    


## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.006  
leftarrow2  <-   1.006


pilefunktion( Knogle_1year_male_340                                                        ,       Knogle_1year_male_340_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Bindevaev_1year_male_350                                                     ,       Bindevaev_1year_male_350_sygdomstekst                                                     , sprog_kode )    



## arrow basic
rightarrow1  <-  0.992
rightarrow2  <-  0.992
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Non_Hodgkin_lymfom_1year_male_360                                            ,       Non_Hodgkin_lymfom_1year_male_360_sygdomstekst                                            , sprog_kode )    

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Hodgkins_lymfom_1year_male_370                                               ,       Hodgkins_lymfom_1year_male_370_sygdomstekst                                               , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Myelomatose_1year_male_380                                                   ,       Myelomatose_1year_male_380_sygdomstekst                                                   , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_1year_male_400                                                      ,       Leukaemi_1year_male_400_sygdomstekst                                                      , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_lymfatisk_leukaemi_1year_male_401                                       ,       Akut_lymfatisk_leukaemi_1year_male_401_sygdomstekst                                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_lymfatisk_leukaemi_1year_male_402                                    ,       Kronisk_lymfatisk_leukaemi_1year_male_402_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403                     ,       Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403_sygdomstekst                     , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_myeloid_leukaemi_1year_male_404                                         ,       Akut_myeloid_leukaemi_1year_male_404_sygdomstekst                                         , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_myeloid_leukaemi_1year_male_405                                      ,       Kronisk_myeloid_leukaemi_1year_male_405_sygdomstekst                                      , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406                       ,       Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406_sygdomstekst                       , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_uspecificerede_celler_1year_male_407                                ,       Leukaemi_uspecificerede_celler_1year_male_407_sygdomstekst                                , sprog_kode )    



## arrow basic  
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.015 
leftarrow2  <-   1.015


pilefunktion( Andre_specificerede_1year_male_410                                           ,       Andre_specificerede_1year_male_410_sygdomstekst                                           , sprog_kode )    





## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ukendte_og_daarligt_definerede_1year_male_420                                ,       Ukendte_og_daarligt_definerede_1year_male_420_sygdomstekst                                , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970        ,       Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970_sygdomstekst        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_1year_male_980                                             ,       Alle_kraeftformer_1year_male_980_sygdomstekst                                             , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_1year_male_990                          ,       Alle_kraeftformer_undtagen_anden_hud_1year_male_990_sygdomstekst                          , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Laebe_mundhule_og_svaelg_1year_male_510                                      ,       Laebe_mundhule_og_svaelg_1year_male_510_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyk_og_endetarm_1year_male_520                                               ,       Tyk_og_endetarm_1year_male_520_sygdomstekst                                               , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Basocellulaere_carcinomer_1year_male_888                                     ,       Basocellulaere_carcinomer_1year_male_888_sygdomstekst                                     , sprog_kode )    



```





```{r female1year,echo=FALSE,eval=TRUE}






## arrow basic
rightarrow1  <-  0.997
rightarrow2  <-  .997
leftarrow1  <-   1.004  
leftarrow2  <-   1.004

pilefunktion( Laebe_1year_female_10                                                          ,       Laebe_1year_female_10_sygdomstekst                                                          , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Mundhule_1year_female_20                                                       ,       Mundhule_1year_female_20_sygdomstekst                                                       , sprog_kode )    




## arrow basic
rightarrow1  <-  .995
rightarrow2  <-  .995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Spytkirtel_1year_female_30                                                     ,       Spytkirtel_1year_female_30_sygdomstekst                                                     , sprog_kode )    


#### FÆRDIGE PLOTS
#### FÆRDIGE PLOTS



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Oropharynx_1year_female_40                                                     ,       Oropharynx_1year_female_40_sygdomstekst                                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nasopharynx_1year_female_41                                                    ,       Nasopharynx_1year_female_41_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.015
leftarrow2  <-   1.015


pilefunktion( Hypopharynx_1year_female_50                                                    ,       Hypopharynx_1year_female_50_sygdomstekst                                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Pharynx_daarligt_defineret_1year_female_51                                     ,       Pharynx_daarligt_defineret_1year_female_51_sygdomstekst                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.02  
leftarrow2  <-   1.02


pilefunktion( Spiseror_1year_female_60                                                       ,       Spiseror_1year_female_60_sygdomstekst                                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.013  
leftarrow2  <-   1.013


pilefunktion( Mave_1year_female_70                                                           ,       Mave_1year_female_70_sygdomstekst                                                           , sprog_kode )    

## arrow basic
rightarrow1  <-  0.988
rightarrow2  <-  0.988
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyndtarm_1year_female_80                                                       ,       Tyndtarm_1year_female_80_sygdomstekst                                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyktarm_1year_female_90                                                        ,       Tyktarm_1year_female_90_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Endetarm_og_anus_1year_female_100                                              ,       Endetarm_og_anus_1year_female_100_sygdomstekst                                              , sprog_kode )    


## arrow basic
rightarrow1  <-  0.967
rightarrow2  <-  0.98
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lever_1year_female_110                                                         ,       Lever_1year_female_110_sygdomstekst                                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.018
leftarrow2  <-   1.018


pilefunktion( Galdeblaere_og_galdeveje_1year_female_120                                      ,       Galdeblaere_og_galdeveje_1year_female_120_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.970
rightarrow2  <-  0.976
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bugspytkirtel_1year_female_130                                                 ,       Bugspytkirtel_1year_female_130_sygdomstekst                                                 , sprog_kode )    



## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.006  
leftarrow2  <-   1.006


pilefunktion( Naese_og_bihuler_1year_female_140                                              ,       Naese_og_bihuler_1year_female_140_sygdomstekst                                              , sprog_kode )    


## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Strube_1year_female_150                                                        ,       Strube_1year_female_150_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lunge_inkl_luftror_1year_female_160                                            ,       Lunge_inkl_luftror_1year_female_160_sygdomstekst                                            , sprog_kode )    

## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lungehinde_1year_female_170                                                    ,       Lungehinde_1year_female_170_sygdomstekst                                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.996
rightarrow2  <-  0.996
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bryst_1year_female_180                                                         ,       Bryst_1year_female_180_sygdomstekst                                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.996
rightarrow2  <-  0.996
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Livmoderhals_1year_female_190                                                  ,       Livmoderhals_1year_female_190_sygdomstekst                                                  , sprog_kode )    




## arrow basic marka
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.0  
leftarrow2  <-   1.0


pilefunktion( Livmoder_1year_female_200                                                      ,       Livmoder_1year_female_200_sygdomstekst                                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_uden_specifikation_1year_female_210                                   ,       Livmoder_uden_specifikation_1year_female_210_sygdomstekst                                   , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Aeggestok_aeggeleder_mv_1year_female_220                                       ,       Aeggestok_aeggeleder_mv_1year_female_220_sygdomstekst                                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ovrige_kvindelige_konsorganer_1year_female_230                                 ,       Ovrige_kvindelige_konsorganer_1year_female_230_sygdomstekst                                 , sprog_kode )    


## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Prostata_1year_female_240                                                      ,       Prostata_1year_female_240_sygdomstekst                                                      , sprog_kode )    






## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Testikel_1year_female_250                                                      ,       Testikel_1year_female_250_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Penis_og_andre_mandlige_konsorganer_1year_female_260                           ,       Penis_og_andre_mandlige_konsorganer_1year_female_260_sygdomstekst                           , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nyre_1year_female_270                                                          ,       Nyre_1year_female_270_sygdomstekst                                                          , sprog_kode )    

## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.006  
leftarrow2  <-   1.006

pilefunktion( Blaere_og_andre_urinveje_1year_female_280                                      ,       Blaere_og_andre_urinveje_1year_female_280_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.996
rightarrow2  <-  0.996
leftarrow1  <-   1.01  
leftarrow2  <-   1.01

pilefunktion( Modermaerkekraeft_hud_1year_female_290                                         ,       Modermaerkekraeft_hud_1year_female_290_sygdomstekst                                         , sprog_kode )    


## arrow basic
rightarrow1  <-  0.997
rightarrow2  <-  0.997
leftarrow1  <-   1.003  
leftarrow2  <-   1.003


pilefunktion( Anden_hud_ikke_modermaerke_1year_female_300                                    ,       Anden_hud_ikke_modermaerke_1year_female_300_sygdomstekst                                    , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Oje_1year_female_310                                                           ,       Oje_1year_female_310_sygdomstekst                                                           , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hjerne_og_centralnervesystem_1year_female_320                                  ,       Hjerne_og_centralnervesystem_1year_female_320_sygdomstekst                                  , sprog_kode )    



## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Skjoldbruskkirtel_1year_female_330                                             ,       Skjoldbruskkirtel_1year_female_330_sygdomstekst                                             , sprog_kode )    




## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Knogle_1year_female_340                                                        ,       Knogle_1year_female_340_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Bindevaev_1year_female_350                                                     ,       Bindevaev_1year_female_350_sygdomstekst                                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.992
rightarrow2  <-  0.992
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Non_Hodgkin_lymfom_1year_female_360                                            ,       Non_Hodgkin_lymfom_1year_female_360_sygdomstekst                                            , sprog_kode )    

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Hodgkins_lymfom_1year_female_370                                               ,       Hodgkins_lymfom_1year_female_370_sygdomstekst                                               , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Myelomatose_1year_female_380                                                   ,       Myelomatose_1year_female_380_sygdomstekst                                                   , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_1year_female_400                                                      ,       Leukaemi_1year_female_400_sygdomstekst                                                      , sprog_kode )    





## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_lymfatisk_leukaemi_1year_female_401                                       ,       Akut_lymfatisk_leukaemi_1year_female_401_sygdomstekst                                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_lymfatisk_leukaemi_1year_female_402                                    ,       Kronisk_lymfatisk_leukaemi_1year_female_402_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403                     ,       Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403_sygdomstekst                     , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_myeloid_leukaemi_1year_female_404                                         ,       Akut_myeloid_leukaemi_1year_female_404_sygdomstekst                                         , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_myeloid_leukaemi_1year_female_405                                      ,       Kronisk_myeloid_leukaemi_1year_female_405_sygdomstekst                                      , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406                       ,       Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406_sygdomstekst                       , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_uspecificerede_celler_1year_female_407                                ,       Leukaemi_uspecificerede_celler_1year_female_407_sygdomstekst                                , sprog_kode )    



## arrow basic 
rightarrow1  <-  0.987
rightarrow2  <-  0.987
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Andre_specificerede_1year_female_410                                           ,       Andre_specificerede_1year_female_410_sygdomstekst                                           , sprog_kode )    





## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ukendte_og_daarligt_definerede_1year_female_420                                ,       Ukendte_og_daarligt_definerede_1year_female_420_sygdomstekst                                , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970        ,       Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970_sygdomstekst        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_1year_female_980                                             ,       Alle_kraeftformer_1year_female_980_sygdomstekst                                             , sprog_kode )    


## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_1year_female_990                          ,       Alle_kraeftformer_undtagen_anden_hud_1year_female_990_sygdomstekst                          , sprog_kode )    

## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Laebe_mundhule_og_svaelg_1year_female_510                                      ,       Laebe_mundhule_og_svaelg_1year_female_510_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyk_og_endetarm_1year_female_520                                               ,       Tyk_og_endetarm_1year_female_520_sygdomstekst                                               , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Basocellulaere_carcinomer_1year_female_888                                     ,       Basocellulaere_carcinomer_1year_female_888_sygdomstekst                                     , sprog_kode )    




```






```{r male5year, echo=FALSE, eval=TRUE}



## arrow basic
rightarrow1  <-  0.997
rightarrow2  <-  0.997
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Laebe_5year_male_10                                                          ,       Laebe_5year_male_10_sygdomstekst                                                          , sprog_kode )    



## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.013
leftarrow2  <-   1.013


pilefunktion( Mundhule_5year_male_20                                                       ,       Mundhule_5year_male_20_sygdomstekst                                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Spytkirtel_5year_male_30                                                     ,       Spytkirtel_5year_male_30_sygdomstekst                                                     , sprog_kode )    



## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Oropharynx_5year_male_40                                                     ,       Oropharynx_5year_male_40_sygdomstekst                                                     , sprog_kode )    



## arrow basic
rightarrow1  <-  0.978
rightarrow2  <-  0.978
leftarrow1  <-   1.018  
leftarrow2  <-   1.018


pilefunktion( Nasopharynx_5year_male_41                                                    ,       Nasopharynx_5year_male_41_sygdomstekst                                                    , sprog_kode )    





## arrow basic
rightarrow1  <-  0.984
rightarrow2  <-  0.984
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hypopharynx_5year_male_50                                                    ,       Hypopharynx_5year_male_50_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Pharynx_daarligt_defineret_5year_male_51                                     ,       Pharynx_daarligt_defineret_5year_male_51_sygdomstekst                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.963
rightarrow2  <-  0.963
leftarrow1  <-   1.035
leftarrow2  <-   1.035


pilefunktion( Spiseror_5year_male_60                                                       ,       Spiseror_5year_male_60_sygdomstekst                                                       , sprog_kode )    


## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1   <-   1.025  
leftarrow2   <-   1.025


pilefunktion( Mave_5year_male_70                                                           ,       Mave_5year_male_70_sygdomstekst                                                           , sprog_kode )    




## arrow basic
rightarrow1  <-  0.98
rightarrow2  <-  0.98
leftarrow1  <-   1.02  
leftarrow2  <-   1.02


pilefunktion( Tyndtarm_5year_male_80                                                       ,       Tyndtarm_5year_male_80_sygdomstekst                                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyktarm_5year_male_90                                                        ,       Tyktarm_5year_male_90_sygdomstekst                                                        , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Endetarm_og_anus_5year_male_100                                              ,       Endetarm_og_anus_5year_male_100_sygdomstekst                                              , sprog_kode )    

## arrow basic
rightarrow1  <-  0.9478
rightarrow2  <-  0.9478
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lever_5year_male_110                                                         ,       Lever_5year_male_110_sygdomstekst                                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Galdeblaere_og_galdeveje_5year_male_120                                      ,       Galdeblaere_og_galdeveje_5year_male_120_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.95
rightarrow2  <-  0.95
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bugspytkirtel_5year_male_130                                                 ,       Bugspytkirtel_5year_male_130_sygdomstekst                                                 , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Naese_og_bihuler_5year_male_140                                              ,       Naese_og_bihuler_5year_male_140_sygdomstekst                                              , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Strube_5year_male_150                                                        ,       Strube_5year_male_150_sygdomstekst                                                        , sprog_kode )    




## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lunge_inkl_luftror_5year_male_160                                            ,       Lunge_inkl_luftror_5year_male_160_sygdomstekst                                            , sprog_kode )    



## arrow basic (kan ikke blive helt rigtig)
rightarrow1  <- 0.9352
rightarrow2  <- 0.9352
leftarrow1  <-  1
leftarrow2  <-  1


pilefunktion( Lungehinde_5year_male_170                                                    ,       Lungehinde_5year_male_170_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bryst_5year_male_180                                                         ,       Bryst_5year_male_180_sygdomstekst                                                         , sprog_kode )    









## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoderhals_5year_male_190                                                  ,       Livmoderhals_5year_male_190_sygdomstekst                                                  , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_5year_male_200                                                      ,       Livmoder_5year_male_200_sygdomstekst                                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_uden_specifikation_5year_male_210                                   ,       Livmoder_uden_specifikation_5year_male_210_sygdomstekst                                   , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Aeggestok_aeggeleder_mv_5year_male_220                                       ,       Aeggestok_aeggeleder_mv_5year_male_220_sygdomstekst                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ovrige_kvindelige_konsorganer_5year_male_230                                 ,       Ovrige_kvindelige_konsorganer_5year_male_230_sygdomstekst                                 , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Prostata_5year_male_240                                                      ,       Prostata_5year_male_240_sygdomstekst                                                      , sprog_kode )    




## arrow basic
rightarrow1  <-  .996
rightarrow2  <-  .996
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Testikel_5year_male_250                                                      ,       Testikel_5year_male_250_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Penis_og_andre_mandlige_konsorganer_5year_male_260                           ,       Penis_og_andre_mandlige_konsorganer_5year_male_260_sygdomstekst                           , sprog_kode )    

## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nyre_5year_male_270                                                          ,       Nyre_5year_male_270_sygdomstekst                                                          , sprog_kode )    






## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Blaere_og_andre_urinveje_5year_male_280                                      ,       Blaere_og_andre_urinveje_5year_male_280_sygdomstekst                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Modermaerkekraeft_hud_5year_male_290                                         ,       Modermaerkekraeft_hud_5year_male_290_sygdomstekst                                         , sprog_kode )    

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Anden_hud_ikke_modermaerke_5year_male_300                                    ,       Anden_hud_ikke_modermaerke_5year_male_300_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Oje_5year_male_310                                                           ,       Oje_5year_male_310_sygdomstekst                                                           , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hjerne_og_centralnervesystem_5year_male_320                                  ,       Hjerne_og_centralnervesystem_5year_male_320_sygdomstekst                                  , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Skjoldbruskkirtel_5year_male_330                                             ,       Skjoldbruskkirtel_5year_male_330_sygdomstekst                                             , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Knogle_5year_male_340                                                        ,       Knogle_5year_male_340_sygdomstekst                                                        , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bindevaev_5year_male_350                                                     ,       Bindevaev_5year_male_350_sygdomstekst                                                     , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Non_Hodgkin_lymfom_5year_male_360                                            ,       Non_Hodgkin_lymfom_5year_male_360_sygdomstekst                                            , sprog_kode )    


## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Hodgkins_lymfom_5year_male_370                                               ,       Hodgkins_lymfom_5year_male_370_sygdomstekst                                               , sprog_kode )    



## arrow basic
rightarrow1  <-  0.986
rightarrow2  <-  0.986
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Myelomatose_5year_male_380                                                   ,       Myelomatose_5year_male_380_sygdomstekst                                                   , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_5year_male_400                                                      ,       Leukaemi_5year_male_400_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_lymfatisk_leukaemi_5year_male_401                                       ,       Akut_lymfatisk_leukaemi_5year_male_401_sygdomstekst                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_lymfatisk_leukaemi_5year_male_402                                    ,       Kronisk_lymfatisk_leukaemi_5year_male_402_sygdomstekst                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403                     ,       Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403_sygdomstekst                     , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_myeloid_leukaemi_5year_male_404                                         ,       Akut_myeloid_leukaemi_5year_male_404_sygdomstekst                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_myeloid_leukaemi_5year_male_405                                      ,       Kronisk_myeloid_leukaemi_5year_male_405_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406                       ,       Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406_sygdomstekst                       , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_uspecificerede_celler_5year_male_407                                ,       Leukaemi_uspecificerede_celler_5year_male_407_sygdomstekst                                , sprog_kode )    


## arrow basic   
rightarrow1  <-  0.9770
rightarrow2  <-  0.9820
leftarrow1  <-   1.02739  
leftarrow2  <-   1.02739


pilefunktion( Andre_specificerede_5year_male_410                                           ,       Andre_specificerede_5year_male_410_sygdomstekst                                           , sprog_kode )    




## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ukendte_og_daarligt_definerede_5year_male_420                                ,       Ukendte_og_daarligt_definerede_5year_male_420_sygdomstekst                                , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970        ,       Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970_sygdomstekst        , sprog_kode )    

## arrow basic
rightarrow1  <-  0.983
rightarrow2  <-  0.983
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_5year_male_980                                             ,       Alle_kraeftformer_5year_male_980_sygdomstekst                                             , sprog_kode )    

## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_5year_male_990                          ,       Alle_kraeftformer_undtagen_anden_hud_5year_male_990_sygdomstekst                          , sprog_kode )    


## arrow basic
rightarrow1  <-  0.987
rightarrow2  <-  0.987
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Laebe_mundhule_og_svaelg_5year_male_510                                      ,       Laebe_mundhule_og_svaelg_5year_male_510_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyk_og_endetarm_5year_male_520                                               ,       Tyk_og_endetarm_5year_male_520_sygdomstekst                                               , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Basocellulaere_carcinomer_5year_male_888                                     ,       Basocellulaere_carcinomer_5year_male_888_sygdomstekst                                     , sprog_kode )    



```







```{r female5year, echo=FALSE,eval=TRUE}

## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005  
leftarrow2  <-   1.005


pilefunktion( Laebe_5year_female_10                                                          ,       Laebe_5year_female_10_sygdomstekst                                                          , sprog_kode )    



## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Mundhule_5year_female_20                                                       ,       Mundhule_5year_female_20_sygdomstekst                                                       , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Spytkirtel_5year_female_30                                                     ,       Spytkirtel_5year_female_30_sygdomstekst                                                     , sprog_kode )    




## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Oropharynx_5year_female_40                                                     ,       Oropharynx_5year_female_40_sygdomstekst                                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.978
rightarrow2  <-  0.978
leftarrow1  <-   1.0229
leftarrow2  <-   1.0229


pilefunktion( Nasopharynx_5year_female_41                                                    ,       Nasopharynx_5year_female_41_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hypopharynx_5year_female_50                                                    ,       Hypopharynx_5year_female_50_sygdomstekst                                                    , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Pharynx_daarligt_defineret_5year_female_51                                     ,       Pharynx_daarligt_defineret_5year_female_51_sygdomstekst                                     , sprog_kode )    


## arrow basic
rightarrow1  <-  0.963
rightarrow2  <-  0.963
leftarrow1  <-   1.035
leftarrow2  <-   1.035


pilefunktion( Spiseror_5year_female_60                                                       ,       Spiseror_5year_female_60_sygdomstekst                                                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.025  
leftarrow2  <-   1.025


pilefunktion( Mave_5year_female_70                                                           ,       Mave_5year_female_70_sygdomstekst                                                           , sprog_kode )    



## arrow basic
rightarrow1  <-  0.986
rightarrow2  <-  0.986
leftarrow1  <-   1.02  
leftarrow2  <-   1.02


pilefunktion( Tyndtarm_5year_female_80                                                       ,       Tyndtarm_5year_female_80_sygdomstekst                                                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyktarm_5year_female_90                                                        ,       Tyktarm_5year_female_90_sygdomstekst                                                        , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Endetarm_og_anus_5year_female_100                                              ,       Endetarm_og_anus_5year_female_100_sygdomstekst                                              , sprog_kode )    


## arrow basic
rightarrow1  <-  0.954
rightarrow2  <-  0.954
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lever_5year_female_110                                                         ,       Lever_5year_female_110_sygdomstekst                                                         , sprog_kode )    


## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.03
leftarrow2  <-   1.03


pilefunktion( Galdeblaere_og_galdeveje_5year_female_120                                      ,       Galdeblaere_og_galdeveje_5year_female_120_sygdomstekst                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.95
rightarrow2  <-  0.95
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bugspytkirtel_5year_female_130                                                 ,       Bugspytkirtel_5year_female_130_sygdomstekst                                                 , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Naese_og_bihuler_5year_female_140                                              ,       Naese_og_bihuler_5year_female_140_sygdomstekst                                              , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Strube_5year_female_150                                                        ,       Strube_5year_female_150_sygdomstekst                                                        , sprog_kode )    




## arrow basic
rightarrow1  <-  0.97
rightarrow2  <-  0.97
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Lunge_inkl_luftror_5year_female_160                                            ,       Lunge_inkl_luftror_5year_female_160_sygdomstekst                                            , sprog_kode )    




## arrow basic (kan ikke blive helt rigtig)
rightarrow1  <- 0.9352
rightarrow2  <- 0.9352
leftarrow1  <-  1.06
leftarrow2  <-  1.06


pilefunktion( Lungehinde_5year_female_170                                                    ,       Lungehinde_5year_female_170_sygdomstekst                                                    , sprog_kode )    


## arrow basic
rightarrow1  <-  0.996
rightarrow2  <-  0.996
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bryst_5year_female_180                                                         ,       Bryst_5year_female_180_sygdomstekst                                                         , sprog_kode )    




## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoderhals_5year_female_190                                                  ,       Livmoderhals_5year_female_190_sygdomstekst                                                  , sprog_kode )    




## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_5year_female_200                                                      ,       Livmoder_5year_female_200_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Livmoder_uden_specifikation_5year_female_210                                   ,       Livmoder_uden_specifikation_5year_female_210_sygdomstekst                                   , sprog_kode )    


## arrow basic
rightarrow1  <-  0.986
rightarrow2  <-  0.986
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Aeggestok_aeggeleder_mv_5year_female_220                                       ,       Aeggestok_aeggeleder_mv_5year_female_220_sygdomstekst                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ovrige_kvindelige_konsorganer_5year_female_230                                 ,       Ovrige_kvindelige_konsorganer_5year_female_230_sygdomstekst                                 , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Prostata_5year_female_240                                                      ,       Prostata_5year_female_240_sygdomstekst                                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  .996
rightarrow2  <-  .996
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Testikel_5year_female_250                                                      ,       Testikel_5year_female_250_sygdomstekst                                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Penis_og_andre_mandlige_konsorganer_5year_female_260                           ,       Penis_og_andre_mandlige_konsorganer_5year_female_260_sygdomstekst                           , sprog_kode )    


## arrow basic
rightarrow1  <-  0.985
rightarrow2  <-  0.985
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Nyre_5year_female_270                                                          ,       Nyre_5year_female_270_sygdomstekst                                                          , sprog_kode )    



## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Blaere_og_andre_urinveje_5year_female_280                                      ,       Blaere_og_andre_urinveje_5year_female_280_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Modermaerkekraeft_hud_5year_female_290                                         ,       Modermaerkekraeft_hud_5year_female_290_sygdomstekst                                         , sprog_kode )    



## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Anden_hud_ikke_modermaerke_5year_female_300                                    ,       Anden_hud_ikke_modermaerke_5year_female_300_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.994
rightarrow2  <-  0.994
leftarrow1  <-   1.007  
leftarrow2  <-   1.007


pilefunktion( Oje_5year_female_310                                                           ,       Oje_5year_female_310_sygdomstekst                                                           , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Hjerne_og_centralnervesystem_5year_female_320                                  ,       Hjerne_og_centralnervesystem_5year_female_320_sygdomstekst                                  , sprog_kode )    






## arrow basic
rightarrow1  <-  0.993
rightarrow2  <-  0.993
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Skjoldbruskkirtel_5year_female_330                                             ,       Skjoldbruskkirtel_5year_female_330_sygdomstekst                                             , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Knogle_5year_female_340                                                        ,       Knogle_5year_female_340_sygdomstekst                                                        , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Bindevaev_5year_female_350                                                     ,       Bindevaev_5year_female_350_sygdomstekst                                                     , sprog_kode )    





## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Non_Hodgkin_lymfom_5year_female_360                                            ,       Non_Hodgkin_lymfom_5year_female_360_sygdomstekst                                            , sprog_kode )    




## arrow basic
rightarrow1  <-  0.995
rightarrow2  <-  0.995
leftarrow1  <-   1.005
leftarrow2  <-   1.005


pilefunktion( Hodgkins_lymfom_5year_female_370                                               ,       Hodgkins_lymfom_5year_female_370_sygdomstekst                                               , sprog_kode )    




## arrow basic
rightarrow1  <-  0.986
rightarrow2  <-  0.986
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Myelomatose_5year_female_380                                                   ,       Myelomatose_5year_female_380_sygdomstekst                                                   , sprog_kode )    





## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_5year_female_400                                                      ,       Leukaemi_5year_female_400_sygdomstekst                                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_lymfatisk_leukaemi_5year_female_401                                       ,       Akut_lymfatisk_leukaemi_5year_female_401_sygdomstekst                                       , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_lymfatisk_leukaemi_5year_female_402                                    ,       Kronisk_lymfatisk_leukaemi_5year_female_402_sygdomstekst                                    , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403                     ,       Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403_sygdomstekst                     , sprog_kode )    





## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Akut_myeloid_leukaemi_5year_female_404                                         ,       Akut_myeloid_leukaemi_5year_female_404_sygdomstekst                                         , sprog_kode )    




## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Kronisk_myeloid_leukaemi_5year_female_405                                      ,       Kronisk_myeloid_leukaemi_5year_female_405_sygdomstekst                                      , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406                       ,       Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406_sygdomstekst                       , sprog_kode )    

## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Leukaemi_uspecificerede_celler_5year_female_407                                ,       Leukaemi_uspecificerede_celler_5year_female_407_sygdomstekst                                , sprog_kode )    




## arrow basic 
rightarrow1  <-  0.9796
rightarrow2  <-  0.9796
leftarrow1  <-   1.01999
leftarrow2  <-   1.01999


pilefunktion( Andre_specificerede_5year_female_410                                           ,       Andre_specificerede_5year_female_410_sygdomstekst                                           , sprog_kode )    





## arrow basic
rightarrow1  <-  0.96
rightarrow2  <-  0.96
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Ukendte_og_daarligt_definerede_5year_female_420                                ,       Ukendte_og_daarligt_definerede_5year_female_420_sygdomstekst                                , sprog_kode )    



## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970        ,       Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970_sygdomstekst        , sprog_kode )    


## arrow basic
rightarrow1  <-  0.989
rightarrow2  <-  0.989
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_5year_female_980                                             ,       Alle_kraeftformer_5year_female_980_sygdomstekst                                             , sprog_kode )    





## arrow basic
rightarrow1  <-  0.989
rightarrow2  <-  0.989
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Alle_kraeftformer_undtagen_anden_hud_5year_female_990                          ,       Alle_kraeftformer_undtagen_anden_hud_5year_female_990_sygdomstekst                          , sprog_kode )    




## arrow basic
rightarrow1  <-  0.987
rightarrow2  <-  0.987
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Laebe_mundhule_og_svaelg_5year_female_510                                      ,       Laebe_mundhule_og_svaelg_5year_female_510_sygdomstekst                                      , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Tyk_og_endetarm_5year_female_520                                               ,       Tyk_og_endetarm_5year_female_520_sygdomstekst                                               , sprog_kode )    


## arrow basic
rightarrow1  <-  0.99
rightarrow2  <-  0.99
leftarrow1  <-   1.01  
leftarrow2  <-   1.01


pilefunktion( Basocellulaere_carcinomer_5year_female_888                                     ,       Basocellulaere_carcinomer_5year_female_888_sygdomstekst                                     , sprog_kode )    


# Sys.sleep(20) # is this really necessary? I have tried to turn it off now 12SEP2017

```










