Laebe_1year_male_10_sygdomstekst                                                               <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Læbe, mænd"
Mundhule_1year_male_20_sygdomstekst                                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Mundhule, mænd"
Spytkirtel_1year_male_30_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Spytkirtel, mænd"
Oropharynx_1year_male_40_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Oropharynx, mænd"
Nasopharynx_1year_male_41_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Nasopharynx, mænd"
Hypopharynx_1year_male_50_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hypopharynx, mænd"
Pharynx_daarligt_defineret_1year_male_51_sygdomstekst                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Pharynx, dårligt defineret, mænd"
Spiseror_1year_male_60_sygdomstekst                                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Spiserør, mænd"
Mave_1year_male_70_sygdomstekst                                                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Mave, mænd"
Tyndtarm_1year_male_80_sygdomstekst                                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyndtarm, mænd"
Tyktarm_1year_male_90_sygdomstekst                                                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyktarm, mænd"
Endetarm_og_anus_1year_male_100_sygdomstekst                                                   <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Endetarm og anus, mænd"
Lever_1year_male_110_sygdomstekst                                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lever, mænd"
Galdeblaere_og_galdeveje_1year_male_120_sygdomstekst                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Galdeblære og galdeveje, mænd"
Bugspytkirtel_1year_male_130_sygdomstekst                                                      <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bugspytkirtel, mænd"
Naese_og_bihuler_1year_male_140_sygdomstekst                                                   <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Næse og bihuler, mænd"
Strube_1year_male_150_sygdomstekst                                                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Strube, mænd"
Lunge_inkl_luftror_1year_male_160_sygdomstekst                                                 <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lunge (inkl. luftrør), mænd"
Lungehinde_1year_male_170_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lungehinde, mænd"
Bryst_1year_male_180_sygdomstekst                                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bryst, mænd"
Livmoderhals_1year_male_190_sygdomstekst                                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoderhals, mænd"
Livmoder_1year_male_200_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoder, mænd"
Livmoder_uden_specifikation_1year_male_210_sygdomstekst                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoder uden specifikation, mænd"
Aeggestok_aeggeleder_mv_1year_male_220_sygdomstekst                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Æggestok, æggeleder mv., mænd"
Ovrige_kvindelige_konsorganer_1year_male_230_sygdomstekst                                      <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Øvrige kvindelige kønsorganer, mænd"
Prostata_1year_male_240_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Prostata, mænd"
Testikel_1year_male_250_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Testikel, mænd"
Penis_og_andre_mandlige_konsorganer_1year_male_260_sygdomstekst                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Penis og andre mandlige kønsorganer, mænd"
Nyre_1year_male_270_sygdomstekst                                                               <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Nyre, mænd"
Blaere_og_andre_urinveje_1year_male_280_sygdomstekst                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Blære og andre urinveje, mænd"
Modermaerkekraeft_hud_1year_male_290_sygdomstekst                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Modermærkekræft, hud, mænd"
Anden_hud_ikke_modermaerke_1year_male_300_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden hud (ikke modermærke), mænd"
Oje_1year_male_310_sygdomstekst                                                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Øje, mænd"
Hjerne_og_centralnervesystem_1year_male_320_sygdomstekst                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hjerne og centralnervesystem, mænd"
Skjoldbruskkirtel_1year_male_330_sygdomstekst                                                  <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Skjoldbruskkirtel, mænd"
Knogle_1year_male_340_sygdomstekst                                                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Knogle, mænd"
Bindevaev_1year_male_350_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bindevæv, mænd"
Non_Hodgkin_lymfom_1year_male_360_sygdomstekst                                                 <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Non- Hodgkin lymfom, mænd"
Hodgkins_lymfom_1year_male_370_sygdomstekst                                                    <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hodgkins lymfom, mænd"
Myelomatose_1year_male_380_sygdomstekst                                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Myelomatose, mænd"
Leukaemi_1year_male_400_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, mænd"
Akut_lymfatisk_leukaemi_1year_male_401_sygdomstekst                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Akut lymfatisk leukæmi, mænd"
Kronisk_lymfatisk_leukaemi_1year_male_402_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Kronisk lymfatisk leukæmi, mænd"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403_sygdomstekst                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret lymfatisk leukæmi, mænd"
Akut_myeloid_leukaemi_1year_male_404_sygdomstekst                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Akut myeloid leukæmi, mænd"
Kronisk_myeloid_leukaemi_1year_male_405_sygdomstekst                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Kronisk myeloid leukæmi, mænd"
Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406_sygdomstekst                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret myeloid leukæmi, mænd"
Leukaemi_uspecificerede_celler_1year_male_407_sygdomstekst                                     <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, uspecificerede celler, mænd"
Andre_specificerede_1year_male_410_sygdomstekst                                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Andre specificerede, mænd"
Ukendte_og_daarligt_definerede_1year_male_420_sygdomstekst                                     <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Ukendte og dårligt definerede, mænd"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970_sygdomstekst             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, bryst og prostata, mænd"
Alle_kraeftformer_1year_male_980_sygdomstekst                                                  <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer, mænd"
Alle_kraeftformer_undtagen_anden_hud_1year_male_990_sygdomstekst                               <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, mænd"
Laebe_mundhule_og_svaelg_1year_male_510_sygdomstekst                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Læbe, mundhule og svælg, mænd"
Tyk_og_endetarm_1year_male_520_sygdomstekst                                                    <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyk- og endetarm, mænd"
Basocellulaere_carcinomer_1year_male_888_sygdomstekst                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Basocellulære carcinomer, mænd"
Laebe_1year_female_10_sygdomstekst                                                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Læbe, kvinder"
Mundhule_1year_female_20_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Mundhule, kvinder"
Spytkirtel_1year_female_30_sygdomstekst                                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Spytkirtel, kvinder"
Oropharynx_1year_female_40_sygdomstekst                                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Oropharynx, kvinder"
Nasopharynx_1year_female_41_sygdomstekst                                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Nasopharynx, kvinder"
Hypopharynx_1year_female_50_sygdomstekst                                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hypopharynx, kvinder"
Pharynx_daarligt_defineret_1year_female_51_sygdomstekst                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Pharynx, dårligt defineret, kvinder"
Spiseror_1year_female_60_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Spiserør, kvinder"
Mave_1year_female_70_sygdomstekst                                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Mave, kvinder"
Tyndtarm_1year_female_80_sygdomstekst                                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyndtarm, kvinder"
Tyktarm_1year_female_90_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyktarm, kvinder"
Endetarm_og_anus_1year_female_100_sygdomstekst                                                 <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Endetarm og anus, kvinder"
Lever_1year_female_110_sygdomstekst                                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lever, kvinder"
Galdeblaere_og_galdeveje_1year_female_120_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Galdeblære og galdeveje, kvinder"
Bugspytkirtel_1year_female_130_sygdomstekst                                                    <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bugspytkirtel, kvinder"
Naese_og_bihuler_1year_female_140_sygdomstekst                                                 <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Næse og bihuler, kvinder"
Strube_1year_female_150_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Strube, kvinder"
Lunge_inkl_luftror_1year_female_160_sygdomstekst                                               <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lunge (inkl. luftrør), kvinder"
Lungehinde_1year_female_170_sygdomstekst                                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Lungehinde, kvinder"
Bryst_1year_female_180_sygdomstekst                                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bryst, kvinder"
Livmoderhals_1year_female_190_sygdomstekst                                                     <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoderhals, kvinder"
Livmoder_1year_female_200_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoder, kvinder"
Livmoder_uden_specifikation_1year_female_210_sygdomstekst                                      <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Livmoder uden specifikation, kvinder"
Aeggestok_aeggeleder_mv_1year_female_220_sygdomstekst                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Æggestok, æggeleder mv., kvinder"
Ovrige_kvindelige_konsorganer_1year_female_230_sygdomstekst                                    <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Øvrige kvindelige kønsorganer, kvinder"
Prostata_1year_female_240_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Prostata, kvinder"
Testikel_1year_female_250_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Testikel, kvinder"
Penis_og_andre_mandlige_konsorganer_1year_female_260_sygdomstekst                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Penis og andre mandlige kønsorganer, kvinder"
Nyre_1year_female_270_sygdomstekst                                                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Nyre, kvinder"
Blaere_og_andre_urinveje_1year_female_280_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Blære og andre urinveje, kvinder"
Modermaerkekraeft_hud_1year_female_290_sygdomstekst                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Modermærkekræft, hud, kvinder"
Anden_hud_ikke_modermaerke_1year_female_300_sygdomstekst                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden hud (ikke modermærke), kvinder"
Oje_1year_female_310_sygdomstekst                                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Øje, kvinder"
Hjerne_og_centralnervesystem_1year_female_320_sygdomstekst                                     <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hjerne og centralnervesystem, kvinder"
Skjoldbruskkirtel_1year_female_330_sygdomstekst                                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Skjoldbruskkirtel, kvinder"
Knogle_1year_female_340_sygdomstekst                                                           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Knogle, kvinder"
Bindevaev_1year_female_350_sygdomstekst                                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Bindevæv, kvinder"
Non_Hodgkin_lymfom_1year_female_360_sygdomstekst                                               <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Non- Hodgkin lymfom, kvinder"
Hodgkins_lymfom_1year_female_370_sygdomstekst                                                  <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Hodgkins lymfom, kvinder"
Myelomatose_1year_female_380_sygdomstekst                                                      <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Myelomatose, kvinder"
Leukaemi_1year_female_400_sygdomstekst                                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, kvinder"
Akut_lymfatisk_leukaemi_1year_female_401_sygdomstekst                                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Akut lymfatisk leukæmi, kvinder"
Kronisk_lymfatisk_leukaemi_1year_female_402_sygdomstekst                                       <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Kronisk lymfatisk leukæmi, kvinder"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403_sygdomstekst                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret lymfatisk leukæmi, kvinder"
Akut_myeloid_leukaemi_1year_female_404_sygdomstekst                                            <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Akut myeloid leukæmi, kvinder"
Kronisk_myeloid_leukaemi_1year_female_405_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Kronisk myeloid leukæmi, kvinder"
Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406_sygdomstekst                          <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret myeloid leukæmi, kvinder"
Leukaemi_uspecificerede_celler_1year_female_407_sygdomstekst                                   <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, uspecificerede celler, kvinder"
Andre_specificerede_1year_female_410_sygdomstekst                                              <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Andre specificerede, kvinder"
Ukendte_og_daarligt_definerede_1year_female_420_sygdomstekst                                   <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Ukendte og dårligt definerede, kvinder"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970_sygdomstekst           <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, bryst og prostata, kvinder"
Alle_kraeftformer_1year_female_980_sygdomstekst                                                <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer, kvinder"
Alle_kraeftformer_undtagen_anden_hud_1year_female_990_sygdomstekst                             <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, kvinder"
Laebe_mundhule_og_svaelg_1year_female_510_sygdomstekst                                         <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Læbe, mundhule og svælg, kvinder"
Tyk_og_endetarm_1year_female_520_sygdomstekst                                                  <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Tyk- og endetarm, kvinder"
Basocellulaere_carcinomer_1year_female_888_sygdomstekst                                        <-             "Forbedring i 1-års relativ kræftoverlevelse, NORDCAN\n Basocellulære carcinomer, kvinder"
Laebe_5year_male_10_sygdomstekst                                                               <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Læbe, mænd"
Mundhule_5year_male_20_sygdomstekst                                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Mundhule, mænd"
Spytkirtel_5year_male_30_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Spytkirtel, mænd"
Oropharynx_5year_male_40_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Oropharynx, mænd"
Nasopharynx_5year_male_41_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Nasopharynx, mænd"
Hypopharynx_5year_male_50_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hypopharynx, mænd"
Pharynx_daarligt_defineret_5year_male_51_sygdomstekst                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Pharynx, dårligt defineret, mænd"
Spiseror_5year_male_60_sygdomstekst                                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Spiserør, mænd"
Mave_5year_male_70_sygdomstekst                                                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Mave, mænd"
Tyndtarm_5year_male_80_sygdomstekst                                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyndtarm, mænd"
Tyktarm_5year_male_90_sygdomstekst                                                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyktarm, mænd"
Endetarm_og_anus_5year_male_100_sygdomstekst                                                   <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Endetarm og anus, mænd"
Lever_5year_male_110_sygdomstekst                                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lever, mænd"
Galdeblaere_og_galdeveje_5year_male_120_sygdomstekst                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Galdeblære og galdeveje, mænd"
Bugspytkirtel_5year_male_130_sygdomstekst                                                      <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bugspytkirtel, mænd"
Naese_og_bihuler_5year_male_140_sygdomstekst                                                   <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Næse og bihuler, mænd"
Strube_5year_male_150_sygdomstekst                                                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Strube, mænd"
Lunge_inkl_luftror_5year_male_160_sygdomstekst                                                 <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lunge (inkl. luftrør), mænd"
Lungehinde_5year_male_170_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lungehinde, mænd"
Bryst_5year_male_180_sygdomstekst                                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bryst, mænd"
Livmoderhals_5year_male_190_sygdomstekst                                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoderhals, mænd"
Livmoder_5year_male_200_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoder, mænd"
Livmoder_uden_specifikation_5year_male_210_sygdomstekst                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoder uden specifikation, mænd"
Aeggestok_aeggeleder_mv_5year_male_220_sygdomstekst                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Æggestok, æggeleder mv., mænd"
Ovrige_kvindelige_konsorganer_5year_male_230_sygdomstekst                                      <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Øvrige kvindelige kønsorganer, mænd"
Prostata_5year_male_240_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Prostata, mænd"
Testikel_5year_male_250_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Testikel, mænd"
Penis_og_andre_mandlige_konsorganer_5year_male_260_sygdomstekst                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Penis og andre mandlige kønsorganer, mænd"
Nyre_5year_male_270_sygdomstekst                                                               <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Nyre, mænd"
Blaere_og_andre_urinveje_5year_male_280_sygdomstekst                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Blære og andre urinveje, mænd"
Modermaerkekraeft_hud_5year_male_290_sygdomstekst                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Modermærkekræft, hud, mænd"
Anden_hud_ikke_modermaerke_5year_male_300_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden hud (ikke modermærke), mænd"
Oje_5year_male_310_sygdomstekst                                                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Øje, mænd"
Hjerne_og_centralnervesystem_5year_male_320_sygdomstekst                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hjerne og centralnervesystem, mænd"
Skjoldbruskkirtel_5year_male_330_sygdomstekst                                                  <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Skjoldbruskkirtel, mænd"
Knogle_5year_male_340_sygdomstekst                                                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Knogle, mænd"
Bindevaev_5year_male_350_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bindevæv, mænd"
Non_Hodgkin_lymfom_5year_male_360_sygdomstekst                                                 <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Non- Hodgkin lymfom, mænd"
Hodgkins_lymfom_5year_male_370_sygdomstekst                                                    <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hodgkins lymfom, mænd"
Myelomatose_5year_male_380_sygdomstekst                                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Myelomatose, mænd"
Leukaemi_5year_male_400_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, mænd"
Akut_lymfatisk_leukaemi_5year_male_401_sygdomstekst                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Akut lymfatisk leukæmi, mænd"
Kronisk_lymfatisk_leukaemi_5year_male_402_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Kronisk lymfatisk leukæmi, mænd"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403_sygdomstekst                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret lymfatisk leukæmi, mænd"
Akut_myeloid_leukaemi_5year_male_404_sygdomstekst                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Akut myeloid leukæmi, mænd"
Kronisk_myeloid_leukaemi_5year_male_405_sygdomstekst                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Kronisk myeloid leukæmi, mænd"
Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406_sygdomstekst                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret myeloid leukæmi, mænd"
Leukaemi_uspecificerede_celler_5year_male_407_sygdomstekst                                     <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, uspecificerede celler, mænd"
Andre_specificerede_5year_male_410_sygdomstekst                                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Andre specificerede, mænd"
Ukendte_og_daarligt_definerede_5year_male_420_sygdomstekst                                     <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Ukendte og dårligt definerede, mænd"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970_sygdomstekst             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, bryst og prostata, mænd"
Alle_kraeftformer_5year_male_980_sygdomstekst                                                  <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer, mænd"
Alle_kraeftformer_undtagen_anden_hud_5year_male_990_sygdomstekst                               <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, mænd"
Laebe_mundhule_og_svaelg_5year_male_510_sygdomstekst                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Læbe, mundhule og svælg, mænd"
Tyk_og_endetarm_5year_male_520_sygdomstekst                                                    <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyk- og endetarm, mænd"
Basocellulaere_carcinomer_5year_male_888_sygdomstekst                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Basocellulære carcinomer, mænd"
Laebe_5year_female_10_sygdomstekst                                                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Læbe, kvinder"
Mundhule_5year_female_20_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Mundhule, kvinder"
Spytkirtel_5year_female_30_sygdomstekst                                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Spytkirtel, kvinder"
Oropharynx_5year_female_40_sygdomstekst                                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Oropharynx, kvinder"
Nasopharynx_5year_female_41_sygdomstekst                                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Nasopharynx, kvinder"
Hypopharynx_5year_female_50_sygdomstekst                                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hypopharynx, kvinder"
Pharynx_daarligt_defineret_5year_female_51_sygdomstekst                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Pharynx, dårligt defineret, kvinder"
Spiseror_5year_female_60_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Spiserør, kvinder"
Mave_5year_female_70_sygdomstekst                                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Mave, kvinder"
Tyndtarm_5year_female_80_sygdomstekst                                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyndtarm, kvinder"
Tyktarm_5year_female_90_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyktarm, kvinder"
Endetarm_og_anus_5year_female_100_sygdomstekst                                                 <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Endetarm og anus, kvinder"
Lever_5year_female_110_sygdomstekst                                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lever, kvinder"
Galdeblaere_og_galdeveje_5year_female_120_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Galdeblære og galdeveje, kvinder"
Bugspytkirtel_5year_female_130_sygdomstekst                                                    <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bugspytkirtel, kvinder"
Naese_og_bihuler_5year_female_140_sygdomstekst                                                 <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Næse og bihuler, kvinder"
Strube_5year_female_150_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Strube, kvinder"
Lunge_inkl_luftror_5year_female_160_sygdomstekst                                               <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lunge (inkl. luftrør), kvinder"
Lungehinde_5year_female_170_sygdomstekst                                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Lungehinde, kvinder"
Bryst_5year_female_180_sygdomstekst                                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bryst, kvinder"
Livmoderhals_5year_female_190_sygdomstekst                                                     <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoderhals, kvinder"
Livmoder_5year_female_200_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoder, kvinder"
Livmoder_uden_specifikation_5year_female_210_sygdomstekst                                      <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Livmoder uden specifikation, kvinder"
Aeggestok_aeggeleder_mv_5year_female_220_sygdomstekst                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Æggestok, æggeleder mv., kvinder"
Ovrige_kvindelige_konsorganer_5year_female_230_sygdomstekst                                    <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Øvrige kvindelige kønsorganer, kvinder"
Prostata_5year_female_240_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Prostata, kvinder"
Testikel_5year_female_250_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Testikel, kvinder"
Penis_og_andre_mandlige_konsorganer_5year_female_260_sygdomstekst                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Penis og andre mandlige kønsorganer, kvinder"
Nyre_5year_female_270_sygdomstekst                                                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Nyre, kvinder"
Blaere_og_andre_urinveje_5year_female_280_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Blære og andre urinveje, kvinder"
Modermaerkekraeft_hud_5year_female_290_sygdomstekst                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Modermærkekræft, hud, kvinder"
Anden_hud_ikke_modermaerke_5year_female_300_sygdomstekst                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden hud (ikke modermærke), kvinder"
Oje_5year_female_310_sygdomstekst                                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Øje, kvinder"
Hjerne_og_centralnervesystem_5year_female_320_sygdomstekst                                     <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hjerne og centralnervesystem, kvinder"
Skjoldbruskkirtel_5year_female_330_sygdomstekst                                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Skjoldbruskkirtel, kvinder"
Knogle_5year_female_340_sygdomstekst                                                           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Knogle, kvinder"
Bindevaev_5year_female_350_sygdomstekst                                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Bindevæv, kvinder"
Non_Hodgkin_lymfom_5year_female_360_sygdomstekst                                               <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Non- Hodgkin lymfom, kvinder"
Hodgkins_lymfom_5year_female_370_sygdomstekst                                                  <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Hodgkins lymfom, kvinder"
Myelomatose_5year_female_380_sygdomstekst                                                      <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Myelomatose, kvinder"
Leukaemi_5year_female_400_sygdomstekst                                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, kvinder"
Akut_lymfatisk_leukaemi_5year_female_401_sygdomstekst                                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Akut lymfatisk leukæmi, kvinder"
Kronisk_lymfatisk_leukaemi_5year_female_402_sygdomstekst                                       <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Kronisk lymfatisk leukæmi, kvinder"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403_sygdomstekst                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret lymfatisk leukæmi, kvinder"
Akut_myeloid_leukaemi_5year_female_404_sygdomstekst                                            <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Akut myeloid leukæmi, kvinder"
Kronisk_myeloid_leukaemi_5year_female_405_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Kronisk myeloid leukæmi, kvinder"
Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406_sygdomstekst                          <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Anden og uspecificeret myeloid leukæmi, kvinder"
Leukaemi_uspecificerede_celler_5year_female_407_sygdomstekst                                   <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Leukæmi, uspecificerede celler, kvinder"
Andre_specificerede_5year_female_410_sygdomstekst                                              <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Andre specificerede, kvinder"
Ukendte_og_daarligt_definerede_5year_female_420_sygdomstekst                                   <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Ukendte og dårligt definerede, kvinder"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970_sygdomstekst           <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, bryst og prostata, kvinder"
Alle_kraeftformer_5year_female_980_sygdomstekst                                                <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer, kvinder"
Alle_kraeftformer_undtagen_anden_hud_5year_female_990_sygdomstekst                             <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Alle kræftformer undtagen anden hud, kvinder"
Laebe_mundhule_og_svaelg_5year_female_510_sygdomstekst                                         <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Læbe, mundhule og svælg, kvinder"
Tyk_og_endetarm_5year_female_520_sygdomstekst                                                  <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Tyk- og endetarm, kvinder"
Basocellulaere_carcinomer_5year_female_888_sygdomstekst                                        <-             "Forbedring i 5-års relativ kræftoverlevelse, NORDCAN\n Basocellulære carcinomer, kvinder"
