Laebe_1year_male_10_sygdomstekst                                                               <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lip, men"
Mundhule_1year_male_20_sygdomstekst                                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oral cavity, men"
Spytkirtel_1year_male_30_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Salivary glands, men"
Oropharynx_1year_male_40_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oropharynx, men"
Nasopharynx_1year_male_41_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Nasopharynx, men"
Hypopharynx_1year_male_50_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Hypopharynx, men"
Pharynx_daarligt_defineret_1year_male_51_sygdomstekst                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pharynx, ill-defined, men"
Spiseror_1year_male_60_sygdomstekst                                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oesophagus, men"
Mave_1year_male_70_sygdomstekst                                                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Stomach, men"
Tyndtarm_1year_male_80_sygdomstekst                                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Small intestine, men"
Tyktarm_1year_male_90_sygdomstekst                                                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Colon, men"
Endetarm_og_anus_1year_male_100_sygdomstekst                                                   <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Rectum and anus, men"
Lever_1year_male_110_sygdomstekst                                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Liver, men"
Galdeblaere_og_galdeveje_1year_male_120_sygdomstekst                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Gallbladder, men"
Bugspytkirtel_1year_male_130_sygdomstekst                                                      <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pancreas, men"
Naese_og_bihuler_1year_male_140_sygdomstekst                                                   <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Nose, sinuses, men"
Strube_1year_male_150_sygdomstekst                                                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Larynx, men"
Lunge_inkl_luftror_1year_male_160_sygdomstekst                                                 <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lung, men"
Lungehinde_1year_male_170_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pleura, men"
Bryst_1year_male_180_sygdomstekst                                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Breast, men"
Livmoderhals_1year_male_190_sygdomstekst                                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Cervix uteri, men"
Livmoder_1year_male_200_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Corpus uteri, men"
Livmoder_uden_specifikation_1year_male_210_sygdomstekst                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Uterus, other, men"
Aeggestok_aeggeleder_mv_1year_male_220_sygdomstekst                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Ovary etc., men"
Ovrige_kvindelige_konsorganer_1year_male_230_sygdomstekst                                      <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other female genital organs, men"
Prostata_1year_male_240_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Prostate, men"
Testikel_1year_male_250_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Testis, men"
Penis_og_andre_mandlige_konsorganer_1year_male_260_sygdomstekst                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Penis etc., men"
Nyre_1year_male_270_sygdomstekst                                                               <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Kidney, men"
Blaere_og_andre_urinveje_1year_male_280_sygdomstekst                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Bladder etc., men"
Modermaerkekraeft_hud_1year_male_290_sygdomstekst                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Melanoma of skin, men"
Anden_hud_ikke_modermaerke_1year_male_300_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Skin, non-melanoma, men"
Oje_1year_male_310_sygdomstekst                                                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Eye, men"
Hjerne_og_centralnervesystem_1year_male_320_sygdomstekst                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Brain, central nervous system, men"
Skjoldbruskkirtel_1year_male_330_sygdomstekst                                                  <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Thyroid, men"
Knogle_1year_male_340_sygdomstekst                                                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Bone, men"
Bindevaev_1year_male_350_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Soft tissues, men"
Non_Hodgkin_lymfom_1year_male_360_sygdomstekst                                                 <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Non-Hodgkin lymphoma, men"
Hodgkins_lymfom_1year_male_370_sygdomstekst                                                    <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Hodgkin lymphoma, men"
Myelomatose_1year_male_380_sygdomstekst                                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Multiple myeloma, men"
Leukaemi_1year_male_400_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Leukaemia, men"
Akut_lymfatisk_leukaemi_1year_male_401_sygdomstekst                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Acute lymphatic leukaemia, men"
Kronisk_lymfatisk_leukaemi_1year_male_402_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Chronic lymphatic leukaemia, men"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_male_403_sygdomstekst                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other and unspecified lymphatic leukaemia, men"
Akut_myeloid_leukaemi_1year_male_404_sygdomstekst                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Acute myeloid leukaemia, men"
Kronisk_myeloid_leukaemi_1year_male_405_sygdomstekst                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Chronic myeloid leukaemia, men"
Anden_og_uspecificeret_myeloid_leukaemi_1year_male_406_sygdomstekst                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other and unspecified myeloid leukaemia, men"
Leukaemi_uspecificerede_celler_1year_male_407_sygdomstekst                                     <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Leukaemia, cell unspecified, men"
Andre_specificerede_1year_male_410_sygdomstekst                                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other specified cancers, men"
Ukendte_og_daarligt_definerede_1year_male_420_sygdomstekst                                     <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Unknown and ill-defined, men"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_male_970_sygdomstekst             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin, breast and prostate cancer, men"
Alle_kraeftformer_1year_male_980_sygdomstekst                                                  <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites, men"
Alle_kraeftformer_undtagen_anden_hud_1year_male_990_sygdomstekst                               <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin cancer, men"
Laebe_mundhule_og_svaelg_1year_male_510_sygdomstekst                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lip, oral cavity and pharynx, men"
Tyk_og_endetarm_1year_male_520_sygdomstekst                                                    <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Colorectal, men"
Basocellulaere_carcinomer_1year_male_888_sygdomstekst                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Basocellular carcinomas, men"
Laebe_1year_female_10_sygdomstekst                                                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lip, women"
Mundhule_1year_female_20_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oral cavity, women"
Spytkirtel_1year_female_30_sygdomstekst                                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Salivary glands, women"
Oropharynx_1year_female_40_sygdomstekst                                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oropharynx, women"
Nasopharynx_1year_female_41_sygdomstekst                                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Nasopharynx, women"
Hypopharynx_1year_female_50_sygdomstekst                                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Hypopharynx, women"
Pharynx_daarligt_defineret_1year_female_51_sygdomstekst                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pharynx, ill-defined, women"
Spiseror_1year_female_60_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Oesophagus, women"
Mave_1year_female_70_sygdomstekst                                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Stomach, women"
Tyndtarm_1year_female_80_sygdomstekst                                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Small intestine, women"
Tyktarm_1year_female_90_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Colon, women"
Endetarm_og_anus_1year_female_100_sygdomstekst                                                 <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Rectum and anus, women"
Lever_1year_female_110_sygdomstekst                                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Liver, women"
Galdeblaere_og_galdeveje_1year_female_120_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Gallbladder, women"
Bugspytkirtel_1year_female_130_sygdomstekst                                                    <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pancreas, women"
Naese_og_bihuler_1year_female_140_sygdomstekst                                                 <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Nose, sinuses, women"
Strube_1year_female_150_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Larynx, women"
Lunge_inkl_luftror_1year_female_160_sygdomstekst                                               <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lung, women"
Lungehinde_1year_female_170_sygdomstekst                                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Pleura, women"
Bryst_1year_female_180_sygdomstekst                                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Breast, women"
Livmoderhals_1year_female_190_sygdomstekst                                                     <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Cervix uteri, women"
Livmoder_1year_female_200_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Corpus uteri, women"
Livmoder_uden_specifikation_1year_female_210_sygdomstekst                                      <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Uterus, other, women"
Aeggestok_aeggeleder_mv_1year_female_220_sygdomstekst                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Ovary etc., women"
Ovrige_kvindelige_konsorganer_1year_female_230_sygdomstekst                                    <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other female genital organs, women"
Prostata_1year_female_240_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Prostate, women"
Testikel_1year_female_250_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Testis, women"
Penis_og_andre_mandlige_konsorganer_1year_female_260_sygdomstekst                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Penis etc., women"
Nyre_1year_female_270_sygdomstekst                                                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Kidney, women"
Blaere_og_andre_urinveje_1year_female_280_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Bladder etc., women"
Modermaerkekraeft_hud_1year_female_290_sygdomstekst                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Melanoma of skin, women"
Anden_hud_ikke_modermaerke_1year_female_300_sygdomstekst                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Skin, non-melanoma, women"
Oje_1year_female_310_sygdomstekst                                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Eye, women"
Hjerne_og_centralnervesystem_1year_female_320_sygdomstekst                                     <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Brain, central nervous system, women"
Skjoldbruskkirtel_1year_female_330_sygdomstekst                                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Thyroid, women"
Knogle_1year_female_340_sygdomstekst                                                           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Bone, women"
Bindevaev_1year_female_350_sygdomstekst                                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Soft tissues, women"
Non_Hodgkin_lymfom_1year_female_360_sygdomstekst                                               <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Non-Hodgkin lymphoma, women"
Hodgkins_lymfom_1year_female_370_sygdomstekst                                                  <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Hodgkin lymphoma, women"
Myelomatose_1year_female_380_sygdomstekst                                                      <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Multiple myeloma, women"
Leukaemi_1year_female_400_sygdomstekst                                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Leukaemia, women"
Akut_lymfatisk_leukaemi_1year_female_401_sygdomstekst                                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Acute lymphatic leukaemia, women"
Kronisk_lymfatisk_leukaemi_1year_female_402_sygdomstekst                                       <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Chronic lymphatic leukaemia, women"
Anden_og_uspecificeret_lymfatisk_leukaemi_1year_female_403_sygdomstekst                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other and unspecified lymphatic leukaemia, women"
Akut_myeloid_leukaemi_1year_female_404_sygdomstekst                                            <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Acute myeloid leukaemia, women"
Kronisk_myeloid_leukaemi_1year_female_405_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Chronic myeloid leukaemia, women"
Anden_og_uspecificeret_myeloid_leukaemi_1year_female_406_sygdomstekst                          <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other and unspecified myeloid leukaemia, women"
Leukaemi_uspecificerede_celler_1year_female_407_sygdomstekst                                   <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Leukaemia, cell unspecified, women"
Andre_specificerede_1year_female_410_sygdomstekst                                              <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Other specified cancers, women"
Ukendte_og_daarligt_definerede_1year_female_420_sygdomstekst                                   <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Unknown and ill-defined, women"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_1year_female_970_sygdomstekst           <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin, breast and prostate cancer, women"
Alle_kraeftformer_1year_female_980_sygdomstekst                                                <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites, women"
Alle_kraeftformer_undtagen_anden_hud_1year_female_990_sygdomstekst                             <-             "Improvement in 1-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin cancer, women"
Laebe_mundhule_og_svaelg_1year_female_510_sygdomstekst                                         <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Lip, oral cavity and pharynx, women"
Tyk_og_endetarm_1year_female_520_sygdomstekst                                                  <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Colorectal, women"
Basocellulaere_carcinomer_1year_female_888_sygdomstekst                                        <-             "Improvement in 1-year relative cancer survival, NORDCAN\n Basocellular carcinomas, women"
Laebe_5year_male_10_sygdomstekst                                                               <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lip, men"
Mundhule_5year_male_20_sygdomstekst                                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oral cavity, men"
Spytkirtel_5year_male_30_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Salivary glands, men"
Oropharynx_5year_male_40_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oropharynx, men"
Nasopharynx_5year_male_41_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Nasopharynx, men"
Hypopharynx_5year_male_50_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Hypopharynx, men"
Pharynx_daarligt_defineret_5year_male_51_sygdomstekst                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pharynx, ill-defined, men"
Spiseror_5year_male_60_sygdomstekst                                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oesophagus, men"
Mave_5year_male_70_sygdomstekst                                                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Stomach, men"
Tyndtarm_5year_male_80_sygdomstekst                                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Small intestine, men"
Tyktarm_5year_male_90_sygdomstekst                                                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Colon, men"
Endetarm_og_anus_5year_male_100_sygdomstekst                                                   <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Rectum and anus, men"
Lever_5year_male_110_sygdomstekst                                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Liver, men"
Galdeblaere_og_galdeveje_5year_male_120_sygdomstekst                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Gallbladder, men"
Bugspytkirtel_5year_male_130_sygdomstekst                                                      <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pancreas, men"
Naese_og_bihuler_5year_male_140_sygdomstekst                                                   <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Nose, sinuses, men"
Strube_5year_male_150_sygdomstekst                                                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Larynx, men"
Lunge_inkl_luftror_5year_male_160_sygdomstekst                                                 <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lung, men"
Lungehinde_5year_male_170_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pleura, men"
Bryst_5year_male_180_sygdomstekst                                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Breast, men"
Livmoderhals_5year_male_190_sygdomstekst                                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Cervix uteri, men"
Livmoder_5year_male_200_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Corpus uteri, men"
Livmoder_uden_specifikation_5year_male_210_sygdomstekst                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Uterus, other, men"
Aeggestok_aeggeleder_mv_5year_male_220_sygdomstekst                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Ovary etc., men"
Ovrige_kvindelige_konsorganer_5year_male_230_sygdomstekst                                      <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other female genital organs, men"
Prostata_5year_male_240_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Prostate, men"
Testikel_5year_male_250_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Testis, men"
Penis_og_andre_mandlige_konsorganer_5year_male_260_sygdomstekst                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Penis etc., men"
Nyre_5year_male_270_sygdomstekst                                                               <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Kidney, men"
Blaere_og_andre_urinveje_5year_male_280_sygdomstekst                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Bladder etc., men"
Modermaerkekraeft_hud_5year_male_290_sygdomstekst                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Melanoma of skin, men"
Anden_hud_ikke_modermaerke_5year_male_300_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Skin, non-melanoma, men"
Oje_5year_male_310_sygdomstekst                                                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Eye, men"
Hjerne_og_centralnervesystem_5year_male_320_sygdomstekst                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Brain, central nervous system, men"
Skjoldbruskkirtel_5year_male_330_sygdomstekst                                                  <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Thyroid, men"
Knogle_5year_male_340_sygdomstekst                                                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Bone, men"
Bindevaev_5year_male_350_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Soft tissues, men"
Non_Hodgkin_lymfom_5year_male_360_sygdomstekst                                                 <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Non-Hodgkin lymphoma, men"
Hodgkins_lymfom_5year_male_370_sygdomstekst                                                    <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Hodgkin lymphoma, men"
Myelomatose_5year_male_380_sygdomstekst                                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Multiple myeloma, men"
Leukaemi_5year_male_400_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Leukaemia, men"
Akut_lymfatisk_leukaemi_5year_male_401_sygdomstekst                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Acute lymphatic leukaemia, men"
Kronisk_lymfatisk_leukaemi_5year_male_402_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Chronic lymphatic leukaemia, men"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_male_403_sygdomstekst                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other and unspecified lymphatic leukaemia, men"
Akut_myeloid_leukaemi_5year_male_404_sygdomstekst                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Acute myeloid leukaemia, men"
Kronisk_myeloid_leukaemi_5year_male_405_sygdomstekst                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Chronic myeloid leukaemia, men"
Anden_og_uspecificeret_myeloid_leukaemi_5year_male_406_sygdomstekst                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other and unspecified myeloid leukaemia, men"
Leukaemi_uspecificerede_celler_5year_male_407_sygdomstekst                                     <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Leukaemia, cell unspecified, men"
Andre_specificerede_5year_male_410_sygdomstekst                                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other specified cancers, men"
Ukendte_og_daarligt_definerede_5year_male_420_sygdomstekst                                     <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Unknown and ill-defined, men"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_male_970_sygdomstekst             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin, breast and prostate cancer, men"
Alle_kraeftformer_5year_male_980_sygdomstekst                                                  <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites, men"
Alle_kraeftformer_undtagen_anden_hud_5year_male_990_sygdomstekst                               <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin cancer, men"
Laebe_mundhule_og_svaelg_5year_male_510_sygdomstekst                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lip, oral cavity and pharynx, men"
Tyk_og_endetarm_5year_male_520_sygdomstekst                                                    <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Colorectal, men"
Basocellulaere_carcinomer_5year_male_888_sygdomstekst                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Basocellular carcinomas, men"
Laebe_5year_female_10_sygdomstekst                                                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lip, women"
Mundhule_5year_female_20_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oral cavity, women"
Spytkirtel_5year_female_30_sygdomstekst                                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Salivary glands, women"
Oropharynx_5year_female_40_sygdomstekst                                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oropharynx, women"
Nasopharynx_5year_female_41_sygdomstekst                                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Nasopharynx, women"
Hypopharynx_5year_female_50_sygdomstekst                                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Hypopharynx, women"
Pharynx_daarligt_defineret_5year_female_51_sygdomstekst                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pharynx, ill-defined, women"
Spiseror_5year_female_60_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Oesophagus, women"
Mave_5year_female_70_sygdomstekst                                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Stomach, women"
Tyndtarm_5year_female_80_sygdomstekst                                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Small intestine, women"
Tyktarm_5year_female_90_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Colon, women"
Endetarm_og_anus_5year_female_100_sygdomstekst                                                 <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Rectum and anus, women"
Lever_5year_female_110_sygdomstekst                                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Liver, women"
Galdeblaere_og_galdeveje_5year_female_120_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Gallbladder, women"
Bugspytkirtel_5year_female_130_sygdomstekst                                                    <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pancreas, women"
Naese_og_bihuler_5year_female_140_sygdomstekst                                                 <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Nose, sinuses, women"
Strube_5year_female_150_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Larynx, women"
Lunge_inkl_luftror_5year_female_160_sygdomstekst                                               <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lung, women"
Lungehinde_5year_female_170_sygdomstekst                                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Pleura, women"
Bryst_5year_female_180_sygdomstekst                                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Breast, women"
Livmoderhals_5year_female_190_sygdomstekst                                                     <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Cervix uteri, women"
Livmoder_5year_female_200_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Corpus uteri, women"
Livmoder_uden_specifikation_5year_female_210_sygdomstekst                                      <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Uterus, other, women"
Aeggestok_aeggeleder_mv_5year_female_220_sygdomstekst                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Ovary etc., women"
Ovrige_kvindelige_konsorganer_5year_female_230_sygdomstekst                                    <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other female genital organs, women"
Prostata_5year_female_240_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Prostate, women"
Testikel_5year_female_250_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Testis, women"
Penis_og_andre_mandlige_konsorganer_5year_female_260_sygdomstekst                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Penis etc., women"
Nyre_5year_female_270_sygdomstekst                                                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Kidney, women"
Blaere_og_andre_urinveje_5year_female_280_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Bladder etc., women"
Modermaerkekraeft_hud_5year_female_290_sygdomstekst                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Melanoma of skin, women"
Anden_hud_ikke_modermaerke_5year_female_300_sygdomstekst                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Skin, non-melanoma, women"
Oje_5year_female_310_sygdomstekst                                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Eye, women"
Hjerne_og_centralnervesystem_5year_female_320_sygdomstekst                                     <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Brain, central nervous system, women"
Skjoldbruskkirtel_5year_female_330_sygdomstekst                                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Thyroid, women"
Knogle_5year_female_340_sygdomstekst                                                           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Bone, women"
Bindevaev_5year_female_350_sygdomstekst                                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Soft tissues, women"
Non_Hodgkin_lymfom_5year_female_360_sygdomstekst                                               <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Non-Hodgkin lymphoma, women"
Hodgkins_lymfom_5year_female_370_sygdomstekst                                                  <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Hodgkin lymphoma, women"
Myelomatose_5year_female_380_sygdomstekst                                                      <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Multiple myeloma, women"
Leukaemi_5year_female_400_sygdomstekst                                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Leukaemia, women"
Akut_lymfatisk_leukaemi_5year_female_401_sygdomstekst                                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Acute lymphatic leukaemia, women"
Kronisk_lymfatisk_leukaemi_5year_female_402_sygdomstekst                                       <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Chronic lymphatic leukaemia, women"
Anden_og_uspecificeret_lymfatisk_leukaemi_5year_female_403_sygdomstekst                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other and unspecified lymphatic leukaemia, women"
Akut_myeloid_leukaemi_5year_female_404_sygdomstekst                                            <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Acute myeloid leukaemia, women"
Kronisk_myeloid_leukaemi_5year_female_405_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Chronic myeloid leukaemia, women"
Anden_og_uspecificeret_myeloid_leukaemi_5year_female_406_sygdomstekst                          <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other and unspecified myeloid leukaemia, women"
Leukaemi_uspecificerede_celler_5year_female_407_sygdomstekst                                   <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Leukaemia, cell unspecified, women"
Andre_specificerede_5year_female_410_sygdomstekst                                              <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Other specified cancers, women"
Ukendte_og_daarligt_definerede_5year_female_420_sygdomstekst                                   <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Unknown and ill-defined, women"
Alle_kraeftformer_undtagen_anden_hud_bryst_og_prostata_5year_female_970_sygdomstekst           <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin, breast and prostate cancer, women"
Alle_kraeftformer_5year_female_980_sygdomstekst                                                <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites, women"
Alle_kraeftformer_undtagen_anden_hud_5year_female_990_sygdomstekst                             <-             "Improvement in 5-year relative cancer survival, NORDCAN\n All sites but non-melanoma skin cancer, women"
Laebe_mundhule_og_svaelg_5year_female_510_sygdomstekst                                         <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Lip, oral cavity and pharynx, women"
Tyk_og_endetarm_5year_female_520_sygdomstekst                                                  <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Colorectal, women"
Basocellulaere_carcinomer_5year_female_888_sygdomstekst                                        <-             "Improvement in 5-year relative cancer survival, NORDCAN\n Basocellular carcinomas, women"
